### ISSUE TITLE
[purchase_discount] missing __init__.py inside of models directory

### ISSUE THREAD

**Issue by TheCloneMaster** [OCA/purchase-workflow#1]
Hi,

After updating directory structure on this module, it now needs **init**.py inside of models doing import of purchase_discount

Still lacking on git skill, so I still don't know how to do the MP to fix this...

**Comment by pedrobaeza** [comment]
See:
https://github.com/OCA/purchase-workflow/pull/2
https://github.com/OCA/purchase-workflow/pull/3
for the corresponding patches.

**Comment by TheCloneMaster** [comment]
Thanks my friend.  I will take some time next week  to learn the git way, so I can propose the fix directly...

**Comment by pedrobaeza** [comment]
I don't understand why the module seems half completed. I was the one that proposed its inclussion, and it was working when I did it. Maybe some files not comitted?

Regards.

**Comment by pedrobaeza** [comment]
I have issued all fixes in the same PR.

Thanks.
