### ISSUE TITLE
Add hacktoberfest label to repository

### ISSUE THREAD

**Issue by carlosdauden** [OCA/purchase-workflow#1002]
Since this year the rules to participate in the hacktoberfest have changed:
https://hacktoberfest.digitalocean.com/hacktoberfest-update
It would be nice to add the label to the repositories so that whoever wants to participate can do so without problems.

Many thanks to the PSCs for the work they do selflessly.

**Comment by legalsylvain** [comment]
Hi. 
1) I don't understand why ? The consequency will be to have noices on our repository. Like bad PR.
2) Please do not open many issues for the same point. It should be talked one time only. (https://github.com/OCA/margin-analysis/issues/86)
