### ISSUE TITLE
[13.0] purchase_delivery_split_date crash with notes and sections with corfirmation

### ISSUE THREAD

**Issue by sergioeix** [OCA/purchase-workflow#1040]
[13.0] Community Ubuntu 18.04 
Steps to reproduce on runbot:
Make a purchase order with a note or section save an try to confirm
![image](https://user-images.githubusercontent.com/62206774/101599294-d221c300-39f9-11eb-914e-c1c3e640984a.png)
Fully reproducible on runbot
B/R

**Comment by mmarcot** [comment]
Same issue #1039
