### ISSUE TITLE
Purchase Request (purchase_request) is assigned doc sequence on "New" and not on "Saved", should we change it?

### ISSUE THREAD

**Issue by kittiu** [OCA/purchase-workflow#1073]
This is always a doubt to me, when some document (also expense in the past) assign sequence this way. Because, the number will be skipped easily without intention.

Should we enhance the module so that, the number is assigned on first "Saved"

@HviorForgeFlow WDYT?

**Comment by HviorForgeFlow** [comment]
Hello @kittiu, it would be great to select only the sequence when saving the Purchase Request. 
:+1:

**Comment by kittiu** [comment]
Hello, I will do the PR for this then. Starting on V14, if you OK.

**Comment by kittiu** [comment]
Done here -> https://github.com/OCA/purchase-workflow/pull/1120
