### ISSUE TITLE
[14.0] purchase_location_by_line : Too many receipts are created

### ISSUE THREAD

**Issue by mmarcot** [OCA/purchase-workflow#1094]
Hello,

When confirming a RfQ having lines with destination location not sorted, it results in too many receipts created.

**Use case:**
- create new RfQ
- add line 1 with destination location WH/Stock
- add line 2 with destination location WH/Stock/Shelf 1
- add line 3 with destination location WH/Stock
- add line 4 with destination location WH/Stock/Shelf 1
- ensure that all lines have the same Delivery Date
- confirm order

**=> It results in 4 receipts created (KO) instead of 2 attended**

**Comment by HviorForgeFlow** [comment]
Solved so closing
