### ISSUE TITLE
Procured purchase grouping

### ISSUE THREAD

**Issue by hippe-67** [OCA/purchase-workflow#1127]
I have a KIT type product
There in two components inside KIT
Component-1 (Purchase from MyVendor#1)
Component-2 (Purchase from MyVendor#2)

Product category -> Procured purchase grouping | No order grouping

These both component goes to same PO. with one vendor.

When we use Standard grouping, Components goes correctly vendors

**Comment by HviorForgeFlow** [comment]
Provide some more information about Odoo version, module name, I barely understand your issue.

**Comment by hippe-67** [comment]
Sorry:
Modul is this: Procured purchase grouping
version is Odoo-13 E
https://github.com/OCA/purchase-workflow/tree/f8f7448f0a2b24ff8536db2e345a989b0138d932/procurement_purchase_no_grouping

**Comment by hippe-67** [comment]
Has anybody investigate this issue?
