### ISSUE TITLE
Discount doesn't goes to the invoice if odoo v8 is configured as invoicing based to incoming shipments.

### ISSUE THREAD

**Issue by antoniocanovas** [OCA/purchase-workflow#115]
When Settings => Purchases => Default invoicing control method => is set to "Based to incoming shipments", the discount is set to "0" in the invoice.

In other configurations ("order purchases" or "order lines") it runs ok.

Thank you.

**Comment by pedrobaeza** [comment]
Antonio, you can check #119 for a proper fix.
