### ISSUE TITLE
[13.0][BUG?] procurement_purchase_no_grouping: missing option?

### ISSUE THREAD

**Issue by Rad0van** [OCA/purchase-workflow#1209]
Not sure if I get this right. In this module I am missing another option (or at least I cannot get it to work that way). Let's assume this scenario:
1. I create SO1 with 3 Products P1(Supplier 1), P2(Supplier 1), P3(Supplier 2).
2. When I confirm I expect 2 PO to be created: PO1(Supplier 1)=[P1, P2] and PO2(Supplier 2)=[P3]
3. I create SO2 with the same content as SO1.
4. When I confirm it I'd expect to have PO3(Supplier 1)=[P1, P2] and PO4(Supplier 2)=[P3]

So what I want to achieve is basically for each SO to have minimal amount of its own(!) POs - that is grouping lines from the same Supplier into same PO. The closest to it is 'order' option but that will cause each product to be in a separate PO.

Can you please confirm I am not missing anything? If so I will develop appropriate code. Any suggestions for naming option that would do that?

Also a side question (@pedrobaeza maybe?): if I assign analytic code to SO that gets propagated to SOL and that gets added to domain in function _make_po_get_domain in procurement_mto_analytic module which prevents any kind of grouping in any case. Is that intentional?

**Comment by pedrobaeza** [comment]
That option is not covered right now. Analytic is taken intentionally for not grouping lines.

**Comment by Rad0van** [comment]
Thanks for quick answer. Will try to implement the required code.

**Comment by Rad0van** [comment]
Implemented (hopefully) in #1211
