### ISSUE TITLE
purchase_discount - apps name conflict

### ISSUE THREAD

**Issue by yvaucher** [OCA/purchase-workflow#122]
Module purchase_discount for series 8.0 belongs to another repository: https://github.com/Vauxoo/addons-vauxoo.git#8.0

@hbto Isn't your version an older one? Can we make this one the reference on apps ?

**Comment by pedrobaeza** [comment]
This is now solved if you see https://www.odoo.com/apps/modules/8.0/purchase_discount/, so I close
