### ISSUE TITLE
Restrict configuration aspects of an app

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/purchase-workflow#123]
Hello! 

After fixing a real mess caused by users with Manager that created new units of measure by mistake, I am thinking to restrict some objects, to be changeable only by a specific group for each app.

The concept is that the differences between the typical groups 'User' and 'Manager' are limited to have better visibility, extra functions (such as advanced reports), or the permission to perform certain actions (such as approving timesheets, etc..).

But it's extremely dangerous that a Manager can have access to the most sensitive configuration aspects of the app. Most of the time managers are the clumsiest of users!. 

For example, in the inventory, a manager is the only person allowed to perform the action "Validate Inventory", but at the same time he can crate a new unit of measure by mistake when he creates a new product (which is an extremely simple error to make).

I am proposing to create a new group for each app, called "Configuration" (e.g. Purchase / Configuration) that is the only one with permission to change the items defined as 'Configuration' in the menus.

As an example you can see the following:
https://github.com/Eficent/eficent-odoo-addons-wip/tree/7.0/purchase_configuration

Please let me know your views.

Regards,
Jordi.

**Comment by pedrobaeza** [comment]
I prefer to disable quick create options with this module: https://github.com/OCA/web/tree/8.0/web_m2x_options.

**Comment by JordiBForgeFlow** [comment]
But then you have to apply this change on every many2one field of every view of every module, right? Because as far as I can see, by default if you don't set it explicitly, this module will not affect the current behaviour.

Regards,
Jordi

**Comment by pedrobaeza** [comment]
Please see https://github.com/OCA/web/tree/8.0/web_m2x_options#irconfig_parameter-options.

**Comment by JordiBForgeFlow** [comment]
Aha! Very nice indeed.  I was looking at version 7.0 of web_m2x_options, and this functionality is not available in that version. I will then port it from 8.0 to 7.0.

**Comment by pedrobaeza** [comment]
The option is implemented already, and this is now not related to this repo. I close.
