### ISSUE TITLE
[12} bug supplier Invoice line is bringing wrong selection field to choose.

### ISSUE THREAD

**Issue by bmessiaz** [OCA/purchase-workflow#1252]
Hello Mr @pedrobaeza 

 I´m testing here the module and found out some issues, perhaps it be my wrong usage ok?

Anyway, please check my remarked items in the images below.

Any doubt, please let me know.

Thanks in advance for your help.

Kind regards.

@bmessiaz

![image](https://user-images.githubusercontent.com/44352660/131025329-e710ef9c-5fa0-4df9-9ffc-03b456df95ee.png)

![image](https://user-images.githubusercontent.com/44352660/131026363-6a955a14-1dad-4fd8-ad28-942792d61953.png)

![image](https://user-images.githubusercontent.com/44352660/131026453-9447f6b5-644f-4d86-b26b-449c06839cc5.png)

![image](https://user-images.githubusercontent.com/44352660/131027000-51c466ba-e459-4d88-9d44-956887b43461.png)

**Comment by pedrobaeza** [comment]
Cost update is not yet implemented
