### ISSUE TITLE
[V13] Purchase Request - PR Line Merged with wrong total quantity when Create the RFQ (Question)

### ISSUE THREAD

**Issue by bunhin** [OCA/purchase-workflow#1271]
Just a question for now, if we have a PR with a product item exist in 2 PR Lines or more with each line quantity, when we create RFQ (both from PR Form or from Purchase Request Lines of Purchase Order App), current behavior is as below:

1. If RFQ created from PR form, Only a line of the product exist in resulted RFQ, but the quantity is only quantity from a PR Line
2. If RFQ created from selected PR lines with same product,  only one line will be on RFQ line, with the total quantity is not correct (it seam just multiplied from a line)  --> to prove create 2 lines of PR with same product with difference qty of each line

Step to repro:
scenario 1  --->create the RFQ from PR Form
1. Create a new PR
2. Add line 1  of produact A  PR qty  = 2
3. Add line 2 of same product (Product A) with PR quantity 1
4. Approve/Confirm the PR
5. Click Create RFQ Button (the two lines is shown in pop up windows)
6. Create the RFQ
7. Current behavior  ---> one line of product A is in created RFQ with quantity only 2

Scenario 2: --> Create the RFQ from Selected Purchase Request Lines of Purchase Order App
A. same of step 1, 2, 3, and 4 above
B. Go to purchase App --> Order --> purchase Request Lines
B.1   the 2 PR lines created are there
B.2   select the 2 PR Lines
B.3   Click Action Create RFQ
B.4    The two lines still shown in the pop windows
B.5   Click to Create RFQ

The resulted RFQ only have one line of product A with quantity = 4

Is it A bug? Or By design PR should not have more than one lines with identical product?

Idea for improvement:
if more than one line is allowed for same product, better to not merge the lines in RFQ  for more right info of PR line status (qty in RFQ)
if only 1 line for a product is allowed in PR, may need a contraint or warning to block

Thank you

**Comment by cramos84** [comment]
Encountered the same problem. When it has 2 equal lines, it fails to pass the amounts.

But if we add the quantity and add it to the current quantity of the generated purchase order then increase more.

In my example I put 5 and 10 quantities of the same product. When placing the order it says 10. But if I add the amount of the current line + the amount of the previous line it gives me 25

**Comment by cramos84** [comment]
I have found the reason for the failure. In the _calc_new_qty method, he checks if that line of the purchase request has already created an order line, and if he finds it, he performs the following loops

`            for prl in po_line.purchase_request_lines:
                for alloc in prl.purchase_request_allocation_ids:
                    rl_qty + = alloc.product_uom_id._compute_quantity (
                        alloc.requested_product_uom_qty, purchase_uom
                    )
`

The problem is that the alloc.requested_product_uom_qty property is always taking the amount of the first line of the purchase request and then it doubles the value of the purchase quote line.

If the following change is made, canceling the second loop the calculation is correct.

`
for prl in po_line.purchase_request_lines:
                # for alloc in prl.purchase_request_allocation_ids:
                rl_qty + = prl.product_uom_id._compute_quantity (
                    prl.product_qty, purchase_uom
                )
`
Any idea why that second loop?

**Comment by R2GTX** [comment]
@cramos84 thank you, you saved my day
