### ISSUE TITLE
Can't approve the Purchase Request eventhough all the tier validation already validated

### ISSUE THREAD

**Issue by hitrosol** [OCA/purchase-workflow#1308]
## Module
purchase_request_tier_validation

## Describe the bug
The flow in V14 is quite different with V13. 
In V14, there is no Confirm button after request the validation, therefore one can't confirm the Purchase Request even though it has been validated by tier validation.

## To Reproduce
V14

1. Install the purchase_request_tier_validation
2. set the tier validation for Purchase Request Model in Setting-Technical-Tier Validation
3. Open new Purchase Request and click button Request Validation, in this step the button Request approval doesn't change to confirm.
4. After all tier validation been validated, use click Request Approval.
5. There is Validation Error as follow:
![image](https://user-images.githubusercontent.com/5949936/144335716-f4ddf08f-4086-4415-a41c-778de64f0e38.png)

**Expected behavior**
After all the tier validation been validated, manager can approve the PR

**Additional context**
I run this db in local and runbot, the error is still the same.

**Comment by hitrosol** [comment]
Hi @kittiu, I try the module before the commit at  https://github.com/OCA/purchase-workflow/commit/77db8b614cdddad20b7d7b1a1469b721a20203cc#diff-0128e96626da93b08c70ac85a5dbd4c64d081285f0a50f921aa87b07e4d2a4aa


and it works as expected. 
![image](https://user-images.githubusercontent.com/5949936/146628136-1636e3a5-2878-48f8-9c92-8a457e82d604.png)


But maybe i missed somethings, the reason you added the 
`_tier_validation_manual_config = False`

and delete some other xml codes there.

**Comment by kittiu** [comment]
OK, I just saw this issue. Looks like the following view change still needed for v14.
```
            <button name="button_approved" position="attributes">
                <attribute
                    name="attrs"
                >{'invisible': ['|','&amp;',('validated', '!=', True),('need_validation', '=', True),'|',('need_validation', '=', True),('state', 'not in', ['draft'])]}</attribute>
                <attribute name="string">Confirm</attribute>
                <attribute
                    name="groups"
                >purchase_request.group_purchase_request_manager</attribute>
            </button>
            <button name="button_to_approve" position="attributes">
                <attribute name="invisible">1</attribute>
            </button>

```

**Comment by kittiu** [comment]
OK, I just saw this issue. Looks like the following view change still needed for v14.
```
            <button name="button_approved" position="attributes">
                <attribute
                    name="attrs"
                >{'invisible': ['|','&amp;',('validated', '!=', True),('need_validation', '=', True),'|',('need_validation', '=', True),('state', 'not in', ['draft'])]}</attribute>
                <attribute name="string">Confirm</attribute>
                <attribute
                    name="groups"
                >purchase_request.group_purchase_request_manager</attribute>
            </button>
            <button name="button_to_approve" position="attributes">
                <attribute name="invisible">1</attribute>
            </button>

```

**Comment by kittiu** [comment]
Fixed here. Can you review please. Thanks.
https://github.com/OCA/purchase-workflow/pull/1332

**Comment by HviorForgeFlow** [comment]
#1332 merged
