### ISSUE TITLE
purchase_order_supplierinfo_update: should it rather be working at the Vendor Bill level?

### ISSUE THREAD

**Issue by dreispt** [OCA/purchase-workflow#1310]
**Is your feature request related to a problem?**

AFAICT the expected flow is:
1. Purchases create the PO. Prices will be set automatically from the known supplier pricelists.
2. Accounting receives the invoice from the supplier. Then createds the Odoo Vendor Bill using the button on the PO. The prices in the Vendor Bill are copied from the PO.
3. Accounting compares the expected prices, already in the Odoo Vendor Bill, with the prices in the supplier invoice. It will then update the Odoo Vendor Bill Prices accordingly.

Following this flow, the supplier price lists will not be updated, since the current feature works at the PO level.

**Describe the solution you'd like**

Having vendor bill product prices update the supplier price lists.

**Describe alternatives you've considered**

This could either be:

a. Added to the current `purchase_order_supplierinfo_update` module, or
b. Be a completely separate module (`account_bill_supplierinfo_update`?)
c. Train the Accounting users to update prices on POs before creating the Vendor Bill (is this good process?)

**Comment by dreispt** [comment]
@pedrobaeza Your thoughts on this would appreciated, thanks!

**Comment by legalsylvain** [comment]
@dreispt this module exists. See account_invoice_supplierinfo_update. (And co)
It is complementary.
Kind regards.

**Comment by dreispt** [comment]
Right @legalsylvain, it is here: https://odoo-community.org/shop/product/account-invoice-supplier-info-update-313
I guess I didn't look into the right branches, thank you.

**Comment by pedrobaeza** [comment]
By our part, to comment that conceptually this module makes the thing "symmetric", as if the creation of the record is done when confirming the purchase order, the update is done on the same place. Anyways, it was our customer requirement, so that was the main reason, hehe.

**Comment by legalsylvain** [comment]
By our part,we need both.
-> on account invoice, because when we receive the supplier invoice, we want to update the supplier info, if price changed 
-> on purchase order, because sometime, the invoice is send some days after the good (or at the end of the month, ...) and we have to update the supplier info before receiving the invoice (and as @pedrobaeza said, to be consistent. For the time being, seems that the feature is half developped in odoo core)

**Comment by pedrobaeza** [comment]
Agreed on both statements.
