### ISSUE TITLE
Installation of purchase_order_line_sequence impossible on big database

### ISSUE THREAD

**Issue by carmenbianca** [OCA/purchase-workflow#1331]
## Module

purchase_order_line_sequence, probably stock_picking_line_sequence by extension.

## Describe the bug

On a database with upwards of 300,000 rows in `purchase_order_line` and `stock_picking` each, the installation of purchase_order_line_sequence is incredibly slow and memory-hungry. It took a decently powerful desktop computer 3 hours of installation before it ran out of memory (12GB limit in Odoo) and aborted installation.

## To Reproduce
**Affected versions**: 12.0

1. Have a big database
2. Install purchase_order_line_sequence

**Expected behavior**

Installation should neither take incredibly long, nor consume so much memory.

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

Fedora 35, Python 3.7.

**Comment by legalsylvain** [comment]
I had the same problem on my odoo instance : 
- purchase.order.line quantity : 1.115.664
- stock.move quantity : 16.203.118

regards.

I think that adding a pre-install hook could solve the problem.

**Comment by carmenbianca** [comment]
This is still a bug afaik. Bump to prevent stale.
