### ISSUE TITLE
[13.0] purchase_invoice_plan wrong invoice totals and tax amounts

### ISSUE THREAD

**Issue by colmeirin** [OCA/purchase-workflow#1366]
## Module
[purchase_invoice_plan](https://github.com/OCA/purchase-workflow/tree/13.0/purchase_invoice_plan)

## Describe the bug
The invoice created by an installment of the invoice plan has an invalid total and tax amount and the move is messed up.

## To Reproduce
**Affected versions**: 13.0

1. Create PO with 1 service product with default 15% tax on runboat.
2. Check "Use Invoice Plan" and add Invoice plan with 10 installments (happens with any number of installments greater than 1).
3. Validate PO.
4. Click button "Create bill by plan".
5. Review wrong invoice

Purchase order to invoice:
![Captura de pantalla 2022-02-24 a las 11 20 01](https://user-images.githubusercontent.com/5647643/155505736-0fd56eb1-4247-4899-b6bb-14bc02c09d48.png)

Invoice created, invoice line is OK, but tax total is wrong:
![Captura de pantalla 2022-02-24 a las 11 03 26](https://user-images.githubusercontent.com/5647643/155505867-c3b431cb-2f6b-42b6-bd2b-396bf1dda769.png)

Move created is wrong:
![Captura de pantalla 2022-02-24 a las 11 03 40](https://user-images.githubusercontent.com/5647643/155506126-65ab6322-8a3e-4a45-bdb6-fb86dc9ae063.png)

**Expected behavior**
Generate a propper invoice with the propper tax amount invoiced and not total.

**Additional context**
Verified locally and on Runboat.

**Comment by colmeirin** [comment]
I looked further into the matter checking "brother" module sale_invoice_plan from OCA/sale-workflow and seems some code is missing to recompute debir/credit lines amounts after creation. I tested it and works OK now with that. Creating a PR to bring that fix to the module

**Comment by Saran440** [comment]
@colmeirin Hi, I test with v14 and 15 is correct.

May be V13 is not update code, Can you cherry-pick this all and test it again, please?
https://github.com/OCA/purchase-workflow/pull/1180
https://github.com/OCA/purchase-workflow/pull/1243
https://github.com/OCA/purchase-workflow/pull/1462
https://github.com/OCA/purchase-workflow/pull/1466
https://github.com/OCA/purchase-workflow/pull/1492
