### ISSUE TITLE
[14] purchase_triple_discount second and triple discount not shown on report

### ISSUE THREAD

**Issue by sergioeix** [OCA/purchase-workflow#1393]
## Module
purchase_triple_discount 

## Describe the bug
Only the first discount is shown on the report

## To Reproduce
**Affected versions**:14

1. set first and second discount on a product
2. print the report and you can see only the first discount is shown
3.

**Expected behavior**
first and second and third discount should be shown if set

**Comment by sergioeix** [comment]
I solved this adding the xml report file from v13 on v14

**Comment by legalsylvain** [comment]
could you make a PR ?

**Comment by sergioeix** [comment]
Done -> Added missing file report_purchase_order.xml #1395
