### ISSUE TITLE
[14.0] purchase_last_price_info not working on multi-company environment with shared products

### ISSUE THREAD

**Issue by antoniocanovas** [OCA/purchase-workflow#1406]
## Module
purchase_last_price_info

## Describe the bug
On multi-company environment with shared products:
- Buy PRODUCT1 on CompanyA => purchase.line.order belongs to CampanyA
- Go to CompanyB => Inventory => Products (kanban) => Change to tree view (ERROR because last_price_info is listed):

Access Error
Due to security restrictions, you are not allowed to access 'Purchase Order Line' (purchase.order.line) records.
Records: [FURN_6666] Acoustic Bloc Screens (id=19)
User: Mitchell Admin (id=2)
This restriction is due to the following rules:
- Purchase Order Line multi-company
Note: this might be a multi-company issue.
Contact your administrator to request access if necessary.

## To Reproduce
**14.0**:

**Expected behavior**
The module must search the purchase.order.line on the current company.

**Additional context**
Tested on runboat with demo data

**Comment by francescapenso** [comment]
i've also found the same issue. Someone is tracking it?
