### ISSUE TITLE
[12.0] purchase_request: field qty_done is not calculating well when flag po_lock on Company is True

### ISSUE THREAD

**Issue by simplify-m110** [OCA/purchase-workflow#1419]
## Module
purchase_request

## Describe the bug
The field qty_done on model purchase.request.line is not calculated well when flag po_lock on Company is set True. This is happen because of the method  _compute_open_product_qty on model purchase.request.allocation which is not calculating the open_product_qty on model purchase.request.allocation if the Purchases order is Locked before the Delivery Order is completed.

@api.depends('requested_product_uom_qty', 'allocated_product_qty',
                 'stock_move_id', 'stock_move_id.state',
                 'stock_move_id.product_uom_qty',
                 'stock_move_id.move_line_ids.qty_done',
                 'purchase_line_id',
                 'purchase_line_id.qty_received',
                 'purchase_state')
    def _compute_open_product_qty(self):
        for rec in self:
            if rec.purchase_state in ['cancel', 'done']:
                rec.open_product_qty = 0.0
            else:
                rec.open_product_qty = \
                    rec.requested_product_uom_qty - rec.allocated_product_qty
                if rec.open_product_qty < 0.0:
                    rec.open_product_qty = 0.0

My proposal solution is to replace the line 
if rec.purchase_state in ['cancel', 'done']:
with
if rec.purchase_state == 'cancel' or (rec.purchase_state == 'done' and not rec.company_id.po_lock):
or 
if rec.purchase_state == 'cancel':

## To Reproduce
**Affected versions**:
12.0

**Comment by StefanRijnhart** [comment]
Please create a PR onto the most recent version of the module with the `if rec.purchase_state == 'cancel':` variant. On the PR, you might want to mention that the `done` state does not indicate the delivery status, which I think is a logical error.

**Comment by simplify-m110** [comment]
> Please create a PR onto the most recent version of the module with the `if rec.purchase_state == 'cancel':` variant. On the PR, you might want to mention that the `done` state does not indicate the delivery status, which I think is a logical error.

Here is the PR:
https://github.com/OCA/purchase-workflow/pull/1422
