### ISSUE TITLE
Field product is not mandatory and the UoM is not filtered by product category of the product

### ISSUE THREAD

**Issue by hitrosol** [OCA/purchase-workflow#1421]
I try the Purchase Request V14 on runboat and found these cases:

Case 1. 
The Product I is not set as mandatory.
The result, after validate the PR, one can't create the RFQ and show this error message
![image](https://user-images.githubusercontent.com/5949936/163133959-24106942-5287-44c5-b3a9-dc07259ae328.png)

This will bring frustrated  of the user since they just know that have to fill the product after the PR approved.
IMO, the message error should shown whenever the user wants to save the form, not after validate it.

Case 2.
In multi UoM set, if the user input the Product, the UoM show all UoM regardless of the UoM category of the product.
It give risk where the user can choose UoM from different UoM category.
Still, the PR can be approved, but can't create the RFQ because of different UoM Category.
![image](https://user-images.githubusercontent.com/5949936/163135644-a5cd3020-44ac-4a38-bac5-219b0d4d9f43.png)

Regards,

**Comment by HviorForgeFlow** [comment]
@hitrosol could you review this PR that is trying to solve your issues, thanks!
