### ISSUE TITLE
[15.0] purchase_receipt_expectation_manual - bug with procurements

### ISSUE THREAD

**Issue by saxomanu** [OCA/purchase-workflow#1522]
purchase_receipt_expectation_manual 

When you have reordering rule for a product and confirmed PO in manuel receive mode without stock picking generated, a new PO is created when the resplanishement scheduler run

## To Reproduce

**Affected versions**: 15

1. Create Reordering rule for a product
2. Make sale order with this product
3. A new Purchase order is created by resplanishement scheduler
4. Go on this PO, choose manual receipt
5. Confirm this PO
6. Run resplanishement scheduler
7. A new PO is created.

**Expected behavior**
No new PO need because of the manual receipt is pending

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by saxomanu** [comment]
@silvioc2c

**Comment by SilvioC2C** [comment]
@saxomanu thanks for signalling this issue. I'll try to take a look at it as soon as possible, if noone tackles it before.
