### ISSUE TITLE
purchase_lot: depends on stock_restrict_lot instead of sale_order_lot_selection

### ISSUE THREAD

**Issue by pafnow** [OCA/purchase-workflow#1538]
**Describe the solution you'd like**
The purchase_lot module depends on sale_order_lot_selection which depends on stock_restrict_lot.
Looking at the interaction between those 3 modules, I think purchase_lot could depends directly on stock_restrict_lot so that it can be used without sale_order_lot_selection.
I found this use case because I might need to put in place another lot creation/selection mechanism than the one offered by sale_order_lot_selection

Please let me know if I'm wrong in my understanding
@florian-dacosta

**Comment by florian-dacosta** [comment]
Hello @pafnow 
Sorry I just see that now that it closed...
But yes, I agree, it could depend only on stock_restrict_lot and just put sale_order_lot_selection as an example of use case in the README.
If you want to make a PR with the change, it is great
