### ISSUE TITLE
Odoo - Purchase order lines with discounts error when confirming RFQ

### ISSUE THREAD

**Issue by matijagu** [OCA/purchase-workflow#1540]
## Module
Purchase order lines with discounts 

## Describe the bug
When confirming RFQ with discount set there is error "RecursionError: maximum recursion depth exceeded while calling a Python object"

Here you can see full error https://docs.google.com/document/d/1gDhzrLWNmwMf1QM5rAiT9FL0oDId7dJcnZ17gXQRfNM/edit?usp=sharing

## To Reproduce
**Affected versions**:
Odoo version 14, plugin version 14.0.1.0.2

1. Create Request for quotation add vendor and products
2. Add discount to product(s)
3. Click on confirm order

**Expected behavior**
When clicking confirm order (step 3) order should be confirmed - without error.

**Additional context**
There was no change in code of this or any module prior to this error message - it worked fine two days ago and now it's not working any more.

**Comment by bigboss97lnt** [comment]
Same thing here! But I'm using Odoo 15
