### ISSUE TITLE
14.0 [purchase_order_line_sequence]

### ISSUE THREAD

**Issue by matteoopenf** [OCA/purchase-workflow#1565]
## Module
purchase_order_line_sequence

## Describe the bug
it's not possibile  install  the module

## To Reproduce

- [ ] 14.0 https://github.com/OCA/purchase-workflow/pull/1564

1. try to install
2.  it' s not present the button to install

**Expected behavior**
it's possibile to install

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by matteoopenf** [comment]
@andreampiovesana

**Comment by bosd** [comment]
PR in #1564

**Comment by matteoopenf** [comment]
https://github.com/OCA/purchase-workflow/pull/1933 fix the problem
