### ISSUE TITLE
[14.0] purchase_manual_currency conversion doesn't calculate value with the manual rate

### ISSUE THREAD

**Issue by tv-openbig** [OCA/purchase-workflow#1758]
purchase_manual_currency currency conversion doesn't calculate anything

## Module
purchase_manual_currency

## Describe the bug

There is no currency conversion in the PO, after changing to a foreign currency 
and applying a individual currency rate which is different from the current 
Odoo standard currency rate. 

## To Reproduce
**Affected versions**: at least 14.0

I switch to a german company.
Main currency is EUR.
Current Currency rate is 0.90000 in Accounting / Settings / Currency
I have a product with a purchase price of 100,00 €
I want to create a purchase in USD.
If i switch in my draft purchase order to USD and apply the manual rate 1.50000 i 
would expect that Odoo would re-calculate the purchase order line from 100,00 
€ to 150,00 USD.

For sure i also tried to save the new individual currency rate before adding a new Po line.

**Expected behavior**
If i switch in my draft purchase order to USD and apply the manual rate 1.50000 i 
would expect that Odoo would re-calculate the purchase order line from 100,00 
€ to 150,00 USD.

**Additional context**

I have recorded a video:
https://drive.google.com/file/d/1ZVhI8hyp__0KxUr54Uem7e7TkoTVqZDG/view

**Comment by Saran440** [comment]
@tv-openbig Hi,
The purpose of this module is base for keep the exchange rate information only. So, you can use this field for do something.

Example with V15
We use this module for check budget https://github.com/ecosoft-odoo/budgeting/tree/15.0/budget_control_purchase_manual_currency

Currency Rate 1 USD = 0.94 EUR (Main currency = EUR)
but we need rate 1USD = 0.90 EUR
1 line = 100 USD

When confirm PO, it will convert 100USD to 90 EUR (convert by manual rate) and commit budget = 90 EUR
