### ISSUE TITLE
Change purchase_discount depdency from purchase_stock to puchase

### ISSUE THREAD

**Issue by RemiFr82** [OCA/purchase-workflow#1794]
Hello @pedrobaeza I don't really know if this is the right way to post my need but I got that you've handeled it in v12.0...

**Is your feature request related to a problem?**
I currently don't use stocks as I'm buying consumables and services and I'm only selling services.
I want to manage discounts on my supplier pricelists but as the puchase_discount module is currently written, it depends on purchase_stock module, which depends on stock module.

**Describe the solution you'd like**
Remove `models/stock_move.py` file.
Remove `_get_stock_move_price_unit()` method from `models/purchase_order.py` file (line 60).
(In both above files, it's written that it could be removed when [https://github.com/odoo/odoo/pull/29983](https://github.com/odoo/odoo/pull/29983) will be merged, but I don't understand what this PR has become...)
Change `purchase_stock` to `purchase` in manifest file (line 16).

**Describe alternatives you've considered**
None, I think this is not a big change...

**Comment by pedrobaeza** [comment]
A split can be considered, but not for this old version.
