### ISSUE TITLE
Problem when selecting items to buy related to the supplier (v16)

### ISSUE THREAD

**Issue by Imen-Felhi** [OCA/purchase-workflow#1801]
## Module
The name of the module that has a bug.
purchase_allowed_product
## Describe the bug

The bug in the selection of a product in the PO lines nothing is displayed in the list
## To Reproduce
**Affected versions**:

1.Configure pla list of sellers in product
2.Enable use_only_supplied_product in partner
3.Creation PO, choose a product in the lines

**Expected behavior**
the need is to display the list of products whose sellers are linked is the same as the supplier selected in the PO
**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by Imen-Felhi** [comment]
A bug when selecting a product in the PO line

**Comment by legalsylvain** [comment]
please edit your message. That is a template, you have fill.
thanks !
