### ISSUE TITLE
[15.0] Purchase Order General Discount Bug: RecursionError: maximum recursion depth exceeded in comparison

### ISSUE THREAD

**Issue by bigboss97lnt** [OCA/purchase-workflow#1824]
## Module
Purchase Order General Discount + Purchase order lines with discounts

## Describe the bug
RFQ not getting confirmed

## To Reproduce
Odoo 15, 
Purchase Order General Discount 15.0.1.0.1
Purchase order lines with discounts 15.0.1.1.0

1. Create RFQ
2. Add general discount
3. Confirm

**Expected behavior**
That RFQ is confirmed

**Additional context**
I've been using the general discount for a while, it did not cause a problem until now and we did not change anything related to the PO, someone already reported the same issue but for version 14 and he got abandoned, I hope the same doesn't happen in my case. Thanks.

Check the error [here](https://github.com/OCA/purchase-workflow/files/11087132/RPC_ERROR.txt)

I have found the code that is causing the problem, I'm trying to fix it but I'm not sure if I can. If someone can help it would be great!

purchase_discount/models/purchase_order.py:37
<img width="515" alt="image" src="https://user-images.githubusercontent.com/64983216/228190916-b283ba3e-35b5-47d5-a6d4-ab484f2ff282.png">

UPDATE 1:
I'm using Odoo.sh, I changed the version from the latest to version 15.0.20230306 then it worked, I guess something after this version conflicted with the plugin. I believe that [this](https://github.com/odoo/odoo/commit/e7dfe10c81e69e3eb82b209db25483f29eb557e6) commit has something to do with it.

**Comment by HviorForgeFlow** [comment]
@bigboss97lnt take a look here: https://github.com/OCA/purchase-workflow/pull/1826

**Comment by bigboss97lnt** [comment]
@HviorForgeFlow Thanks! that saved me.

**Comment by HviorForgeFlow** [comment]
Solved
