### ISSUE TITLE
[14][IMP] purchase_order_line_price_history Usability of the history button

### ISSUE THREAD

**Issue by fcvalgar** [OCA/purchase-workflow#1841]
To improve the usability of the purchase order line in relation to the history button.

We would like to propose and develop the improvement of removing the text keeping only the icon as it happens in the last CE of V16.

![P00008-Odoo](https://user-images.githubusercontent.com/17847432/231427852-c76c631d-a6b0-4d18-a1a6-28b0c93bd61e.png)
![Odoo-P00021](https://user-images.githubusercontent.com/17847432/231427854-0b9937c9-99b5-4a92-ae5d-bdab61589d08.png)

If it is agreeable to the maintainers @ernestotejeda. @Moduon would propose the PR.

Thank you.

**Comment by pedrobaeza** [comment]
Yeah, this can be even considered as a bad migration, as the `string` attribute should be transformed into `title`. I'm adding it into the migration guide (https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0). Example of transformation: https://github.com/OCA/project/commit/23fee08ae43258effa39613ce76eb8f4e83650fe

**Comment by fcvalgar** [comment]
> Yeah, this can be even considered as a bad migration, as the `string` attribute should be transformed into `title`. I'm adding it into the migration guide (https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0). Example of transformation: [OCA/project@23fee08](https://github.com/OCA/project/commit/23fee08ae43258effa39613ce76eb8f4e83650fe)

Thank you, @pedrobaeza 

We will propose the PR.

MT-2735 @moduon
