### ISSUE TITLE
[14.0] [purchase_advance_payment] wrong residual amount when reconciling credit note with invoice

### ISSUE THREAD

**Issue by ygol** [OCA/purchase-workflow#1855]
## Module
purchase_advance_payment

## Describe the bug
When reconciling an bill with a vendor credit note, the residual amount is false. As the vendor credit note amount is subtracted twice.

## To Reproduce
tested 14.0

1. create a PO, confirm + create an invoice
2. edit the above PO and add a new line with negative amount, confirm + create bill
3. reconcile the available vendor credit note amount on the vendor bill
4. Get wrong residual amount = 360000
![image](https://user-images.githubusercontent.com/2945174/234322485-14f78896-89ef-4351-95dd-ff7dc3823f41.png)

**Expected behavior**
Residual amount to be 480000

![image](https://user-images.githubusercontent.com/2945174/234322607-9f118d8f-714e-45f7-98b1-031d62dfdddf.png)
**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by ygol** [comment]
the problem is that the PO total amount has already discounted the value of the credit note and when we reconcile the credit note  with the invoice it is thus deducted a 2nd time when https://github.com/OCA/purchase-workflow/blob/c186f0808b932416bb5e1cab563cfd87c2ee4d3b/purchase_advance_payment/models/purchase_order.py#L87

**Comment by HviorForgeFlow** [comment]
ping @MateuGForgeFlow

**Comment by HviorForgeFlow** [comment]
@ygol We will be more than excited to review your fix proposal

**Comment by djtao1** [comment]
I am also very troubled by this issue. Is there a plan or possibility to fix this issue? thanks for support!

**Comment by rvalyi** [comment]
cc @clementmbr @PierrickBrun @NathanQj

**Comment by djtao1** [comment]
I have tested the latest version and it appears to be functioning correctly. but how to correct the erroneous entry caused by this issue earlier. They don't seem to have been automatically corrected.

**Comment by ygol** [comment]
> I have tested the latest version and it appears to be functioning correctly. but how to correct the erroneous entry caused by this issue earlier. They don't seem to have been automatically corrected.

hi @djtao1 working on a solution in #1862
