### ISSUE TITLE
VCI workflow: POS order lines?

### ISSUE THREAD

**Issue by thomasklosinsky** [OCA/purchase-workflow#194]
What about POS order lines?
How can I include these in the whole product ownership workflow?

Wouldn't it be easier to have the product owner directly saved in the product and start the workflow from there and not from the order lines?

???

**Comment by pedrobaeza** [comment]
I don't get the relation of this with the purchase-workflow repository

**Comment by thomasklosinsky** [comment]
:)
Since it's been over a year now I am also lost with this issue ... ;)...
Will let you know when I had the time to check it out...

**Comment by bennals** [comment]
This is of interest to me @thomasklosinsky.
Do you mean that you would like to have the ability to sell consignment stock through the touchscreen POS and have the special Request for Quotation generated in the same way as it is when you enter a sales order?

**Comment by thomasklosinsky** [comment]
Well, yeah. In my case it was that my customer has several items which he didn't buy but had in his store for sale.
Called "commission sale" in Germany. You give the owner the money when you have had sales...
This workflow would be perfect for this kind of sales and stock handle...
You specify an owner of your stuff in the product, sell it through POS and then Odoo generates Supplier Quotations from the POS sale automatically.
Would be great to have ;)...

**Comment by bennals** [comment]
@thomasklosinsky - Yes, that's exactly the situation I have here - 'consignment sale' in Australia.

@pedrobaeza  Does that make sense, or is it still not relevant for this particular workflow.

**Comment by thomasklosinsky** [comment]
@bennals - I was just recently asking a developer for this function and he already gave me an offer. I will see if the customer can afford that. would you be interested in sharing costs for this function?

**Comment by lasley** [comment]
@thomasklosinsky @bennals - The requirements in this issue are pretty vague, but you may want to take a look at [pos_sale_order](https://github.com/OCA/pos/pull/35).

**Comment by bennals** [comment]
@thomasklosinsky yes, depending on the costs of course, no harm in hearing about it though.

@lasley thanks, though that doesn't specifically deal with the vendor consignment aspect of the workflow as far as I can tell.

**Comment by thomasklosinsky** [comment]
I am also not sure if that module would work. It may be the right direction since the consignment stock should work on usual sale orders, but still the workflow is not the best for this usage...
@bennals  cost estimate so far was $300-700... but I will get a closer estimate when talking to the programmer and refine needs. Will be in a week or two. I will keep you updated.

**Comment by bennals** [comment]
@thomasklosinsky sorry about the late reply.  I never get email notifications about mentions or issue updates from Github for some reason (which I should probably look into).  Looking forward to the update.

**Comment by bennals** [comment]
@thomasklosinsky 
Sorry for resurrecting this old issue but did you ever get anywhere with that custom module for Commission Sale (consignment sale here in Aus)?  I'm really in need of the module now!

**Comment by thomasklosinsky** [comment]
@bennals 
sorry. 
I won't be able to make the customization, but if you need a good contact for Odoo/Python customization work, leave me a message. I didn't get any further with this so far.
But if you are asking the guy I have in mind I will ask my customer again if they still want that functionality. Which Odoo version are you using?

**Comment by bennals** [comment]
@thomasklosinsky that's ok, and yes, happy to hear about your contact - it would make sense if they have already been briefed on the job.  I'll be using v11.
