### ISSUE TITLE
Can't get one2many record details after activated purchase tier validation

### ISSUE THREAD

**Issue by Enikish** [OCA/purchase-workflow#1949]
## Module
The name of the module that has a bug.

## To Reproduce
**Affected versions**:

1.
2.
3.

**Expected behavior**

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by pedrobaeza** [comment]
Very few details and not even Odoo version. Try to reproduce it on runboat and give more details.

**Comment by Enikish** [comment]
sry about the previous click.
Here is the issue.
I activated the **purchase tier validation** module, and I used a model with a field which is a one2many refers to the **purchase request**, and when I try to view the details of the requests, I have the error like following:
UncaughtPromiseError
 Missing field string information for the field 'need_validation' from the 'purchase.request' model
If there is any problem I made, please message me and thank you

**Comment by pedrobaeza** [comment]
Are you trying to customize the module for another model? Please specify exact steps to reproduce the problem and Odoo version.

**Comment by Enikish** [comment]
Sorry about the version, my odoo version is 16.0
And I am using the purchase request like this:
    request_ids = fields.One2many(
        string='requests',
        inverse_name='task_id', 
        comodel_name='purchase.request', 
        domain=[('state','=','approved')],
    )
And I show the requests in the task's form view.
before I activate the **purchase request tier validation** module, it can show the details by the form view correctly.
It is happends after activating the purchase request tier validation module, when I try to access the details of requests, it just show the error above.**Missing field string infomation for the field 'need_validation' from the 'purchase.request' model.**
I met this bug many times, the way I solve is just check the id of <record> tag in the corresponding view. But I have no clue to solve this.

**Comment by pedrobaeza** [comment]
Sorry, can't say about custom developments on your side. The module itself is not giving such problems.

**Comment by Enikish** [comment]
ok,thank you
