### ISSUE TITLE
[8.0] [purchase_order_reorder_lines] Error when creatring new purchase order

### ISSUE THREAD

**Issue by OpenCode** [OCA/purchase-workflow#199]
I'm trying to create a new purchase order and i have that error: ValueError: max() arg is an empty sequence.

File "/home/...../purchase-workflow/purchase_order_reorder_lines/purchase.py", line 71, in _get_max_line_sequence
    max(purchase.mapped('order_line.sequence')) + 10
ValueError: max() arg is an empty sequence

**Comment by pedrobaeza** [comment]
That was fixed on https://github.com/OCA/purchase-workflow/commit/ef98e7ff550ef92ad6ab88e7ffbb4d5e71a96f34. Please update your code.
