### ISSUE TITLE
[16] Purchase_discount - Supplier discount not applied on variants

### ISSUE THREAD

**Issue by glissattitude** [OCA/purchase-workflow#1996]
Supplier discount not applied on variants

## Module
Purchase_discount 

## Describe the bug
When adding a product with variants in a purchase order, the variant selection wizard allow variant selection.
When validating, selected products are added to purchase order but for these products, supplier discount is not applied, even if correctly declared in product purchase line info

## To Reproduce
odoo v16

1 - Create supplier S1 with default discount 10%
2 - Create a product P1 with 2 variants
3 - Filling purchase lines for supplier S1 for each variant. At this step, default S1 discount is well applied on lines
4 - Create a purchase PO001 order with supplier S1
5 - Add a purchase line with P1
6 - The variant selection wizard openned
7 - select qty 1 for first variant
8 - Click on Confirm button

**Expected behavior**
The new purchase line for P1 is correctly added to PO001, but the discount value is 0
This discount value should be 10%

**Additional context**
the _onchange_quantity of PurchaseOrderLine class is not triggered when coming from the variant selection wizard
I tried some modifications, like overriding create method of PurchaseOrderLine class but it seams that nothing is triggered when coming back from the wizard (witch I supposed is js managed)

**Comment by legalsylvain** [comment]
Hi @glissattitude Thanks for reporting.
Just a question, what is the "variant selection wizard". Is it native ? Or another module ?

**Comment by glissattitude** [comment]
Hi Sylvain
Yes, this wizard seams to be standard 
![c1](https://github.com/OCA/purchase-workflow/assets/120647351/5a47f102-19e4-4414-bc5b-20cb9cef0513)
![c2](https://github.com/OCA/purchase-workflow/assets/120647351/58049777-4ee2-44c7-bf1b-e7410b38bd64)

**Comment by legalsylvain** [comment]
Hi @glissattitude. Sorry, the second screen that help you to select a variant is not standard. I tested installing the module with purchase and purchase discount and the variant are displayed in the list, not in a popup.
(and the module ``purchase_discount`` works in that case)
![image](https://github.com/OCA/purchase-workflow/assets/3407482/ba66460b-78d1-43ca-b10a-75f974e1b222)

Could you mention the name of the module you installed that provides that feature ? 

thanks !

**Comment by glissattitude** [comment]
Thanks a lot for your concern, 
I'm really surprised, because I didn't install module for that purpose, but I will investigate if it's part of another module we have on our setup.

**Comment by glissattitude** [comment]
After a rapid search, this feature seams to come from product_matrix module, part of the native communautary version
But I don't know what parameter or setup is controlling the display of this type of dialog in place of the list of your screen capture

**Comment by legalsylvain** [comment]
when ``purchase_product_matrix`` is installed, the original dropdownlist that display product.product is hidden, and replaced by a dropdownlist of product.template. once a template is selected, the wizard is displayed, allowing to select quantities for each variant.

If I understand correctly : 
- before V16, there was a core onchange function named ``_onchange_quantity`` that has been replaced in V16 by a compute function named ``_compute_price_unit_and_date_planned_and_name``.  Ref to the commit that changes the logic : https://github.com/odoo/odoo/commit/863c5090f09bfffc2867717ed8b3c99b05a5eb9c (and related PR : https://github.com/odoo/odoo/pull/87656)
- The OCA module in V16, still overload a non existing function _onchange_quantity. 
IMO, the OCA module should now overload _compute_price_unit_and_date_planned_and_name.

OCA PR that port the module in V16 : https://github.com/OCA/purchase-workflow/pull/1602

CC contributors / reviewers : @ramiadavid, @pedrobaeza, @omar7r, @mdietrichc2c, @sbidoul

**Comment by glissattitude** [comment]
Thanks sylvain for this analysis :)

**Comment by glissattitude** [comment]
Sylvain, let me just confirm your opinion 👍 
I have added an override of _compute_price_unit_and_date_planned_and_name in the purchase_order.py file of the module by copying the original code from purchase module. 
Then, I have added 
`self.discount = seller.discount`
just after line
`line.date_planned = line._get_date_planned(seller).strftime(DEFAULT_SERVER_DATETIME_FORMAT)`

And now the behaviour is as expected
now I let specialists of this module to find a more elegant way to solve the issue, and publish an upgrade, but your analysis is correct 
Again thanks a lot for you efficiency

**Comment by pedrobaeza** [comment]
Fix in #2012
