### ISSUE TITLE
7.0: possible conflict in test run

### ISSUE THREAD

**Issue by lepistone** [OCA/purchase-workflow#20]
The 7.0 test run breaks because it does not find an `onchange`. I haven't investigated further, but the error message

https://travis-ci.org/OCA/purchase-workflow/jobs/31600334#L1125

appears in the tests for `purchase_landed_costs`, but the it mentions `framework_agreement`. The modules do not depend on each other.

At a first grance this could be a real incompatibility between the two, or it could be `yaml_import.py` that struggles with inherited onchange methods.

**Comment by gurneyalex** [comment]
I think the culprit is `yaml_import.py`. I've split the tests of framework_agreement out in #21 It clears this problem, but the `purchase_landed_costs` tests are red (#22)

**Comment by gurneyalex** [comment]
closing the issue, keeping #22
