### ISSUE TITLE
purchase_order_revision can't working ..on purchase order..partner id same.

### ISSUE THREAD

**Issue by jaronemo** [OCA/purchase-workflow#202]
Dear Sir:
push this purchase order (PO1601040017)
![image](https://cloud.githubusercontent.com/assets/8476734/12110431/0e432a90-b3c7-11e5-99a3-f89355991b7f.png)

This is odoo log print.
![image](https://cloud.githubusercontent.com/assets/8476734/12110402/d548c70e-b3c6-11e5-93a4-5d63202eb5f7.png)

I dont' know .. WHY?

So..i search purchase order ..from partner...
i get this order...
![image](https://cloud.githubusercontent.com/assets/8476734/12110462/5ce60f0a-b3c7-11e5-8d38-af27c772750b.png)

**Comment by eLBati** [comment]
Hello @jaronemo , can you provide the steps to generate the problem on a new database?

**Comment by jaronemo** [comment]
Hi....@eLbati....
Thanks for your reply.

Follow the following sequence of operations
1.create purchase order ..maybe: PO00001
2.confirm purchase order 
3. cancle this purchase order .name: PO00001
4.new revision ....then create new purhcase order  name i s PO00001-1
5.cancel this purchase order name PO00001-1
6.more->duplicate 
7.new purchase order create...name is PO00002 
8. confirm this order PO00002
9.cancel this order PO00002
10. new revision.....then error
![image](https://cloud.githubusercontent.com/assets/8476734/12270662/25ce7e14-b992-11e5-8690-55956f0383d1.png)

**Comment by eLBati** [comment]
Thank you @jaronemo , please see PR https://github.com/OCA/purchase-workflow/pull/210 should fix the problem
