### ISSUE TITLE
[MIG] From 8.0 to 9.0 - Purchase Request modules

### ISSUE THREAD

**Issue by JonathanNEMRY** [OCA/purchase-workflow#232]

**Comment by JordiBForgeFlow** [comment]
@JonathanNEMRY @sbidoul. We're going to make a sprint this week to port to v9. @aheficent will then follow up on any review comments during the following weeks.

**Comment by sbidoul** [comment]
Great news! We'll test and review as soon as you have pushed something. cc/ @adrienpeiffer @chrisdec

**Comment by JonathanNEMRY** [comment]
Thanks for the new! I'll follow it very closely

**Comment by pedrobaeza** [comment]
Closing this issue as PR has been done.
