### ISSUE TITLE
is that possible to migation purchase_default_terms_conditions to odoo17? thanks.

### ISSUE THREAD

**Issue by djtao1** [OCA/purchase-workflow#2427]
**Is your feature request related to a problem?**
If so, please provide clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by pedrobaeza** [comment]
Look for the progress in https://github.com/OCA/purchase-workflow/issues/2087
