### ISSUE TITLE
Translate Purchase modules

### ISSUE THREAD

**Issue by JonathanNEMRY** [OCA/purchase-workflow#243]
What's the best way to translate some purchase modules? I've requested to join team on transiflex, is it the best solution or maybe I just have to make a PR with .po?

Thanks!

cc @pedrobaeza, @jbeficent

**Comment by JordiBForgeFlow** [comment]
@JonathanNEMRY I'm not familiar with Transifex, so I'll wait and listen on this one ;)

**Comment by pedrobaeza** [comment]
The best solution indeed is to use Transifex: https://www.transifex.com/oca/OCA-purchase-workflow-9-0/dashboard/
