### ISSUE TITLE
[8.0][purchase_request] Ability to approve items from a purchase request

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/purchase-workflow#255]
We have identified a use case by which purchasing wants to be able to decide what items they want to approve for further purchasing (create RFQ or Bid).

SAP uses a similar approach in their Purchase Requisitions. See:
http://web.mit.edu/sapweb/PS1/help/reqs_approve.shtml

What we propose is to introduce a flag 'Approved' in purchase request lines.

Then, have a wizard to approve purchase request lines (so this can done for multiple items at once). 

A purchase request that has not been approved cannot be added to a Bid or RFQ.

Another option is to work on an exclusion basis. Have a check 'Rejected' on the purchase request lines. Purchasing can then decide what items are rejected, and those items cannot be purchased.

cc @JonathanNEMRY, @aheficent

**Comment by sbidoul** [comment]
cc/ @chrisdec

**Comment by chrisdec** [comment]
Hi Jordi, 

To be sure I well understand : the goal of this is to manage partial approbation of purchase requests? 

Because, there is already a state on purchase request lines which is equal to the state of the linked purchase request. So, add this flag allows to have a purchase request line with a different state than the state of the linked purchase request, exact? 

Thanks in advance for the answer,

**Comment by JordiBForgeFlow** [comment]
Yes. Imagine that I create a purchase request as follows:
- 1 Pencil
- 2 Rubbers

When the purchasing department reviews the request,  might find that there are already 2 rubbers in the warehouse, and so they are not truly needed, or perhaps the rubbers are not approved for purchase, put the pencil is acceptable.

Now I find that purchasing may find that 1 out of 20 items on a purchase request should not need to be purchased for one reason or another. The current approach might be to reject the entire request and request to the requester to remove the requested line. If the line is not removed, that request line will be hanging, and in a few days purchasing will not be sure whether this line needs attention or not.

Perhaps the key concept here is that the approval might need to be on the purchase request lines, not in the purchase request. That way, it gives more flexibility to the purchasing department to decide what to accept and what to reject. So the purchase request header is just a method to group the requests that were created together for some reason, and even perhaps could have an option to accept or reject all lines at once.

cc @kittiu @sysadminmatmoz

**Comment by sbidoul** [comment]
@jbeficent interesting idea. It makes sense to me.

What then would be states of the Purchase Request and Purchase Request Line respectively?

**Comment by JordiBForgeFlow** [comment]
@sbidoul Currently the purchase request has the following states:
_STATES = [
    ('draft', 'Draft'),
    ('to_approve', 'To be approved'),
    ('approved', 'Approved'),
    ('rejected', 'Rejected')
]
See: https://github.com/OCA/purchase-workflow/blob/8.0/purchase_request/models/purchase_request.py#L8

The purchase request lines has a field "request_state" that is related to the request status:
    request_state = fields.Selection(string='Request state',
                                     readonly=True,
                                     related='request_id.state',
                                     selection=_STATES,
                                     store=True)
https://github.com/OCA/purchase-workflow/blob/8.0/purchase_request/models/purchase_request.py#L228

I realize that some companies approve in SAP on a header basis, and others do on a line basis.

The proposal could be:
When the user creates a Purchase Request (PR)  and presses the button "To approve" all items change to the status "To approve".

## Scenario 1) Approval on the PR level (current situation)
- Approver changes PR from "To approve" to "Approved" or "Rejected".
- All lines take the status of the PR automatically.

## Scenario 2)  Approval on the PR line level (proposed new use case)
- Approver presses the button "Approve" or "Reject" on a PR line basis, or does it for multiple lines using a wizard.
- Once all lines are "Approved" or "Rejected" the PR status changes to "Approved" (if at least one item was approved) or "Rejected" (all items were rejected)

In any of the two scenarios the approver can reset the whole PR pressing "Reset". This causes the PR to be set to status "Draft" again, for all lines.

In Purchasing / Configuration there could be an option:
[ ] Approve Purchase Requests on a per-line basis

I don't think that we should take this kind of change lightly. Scenario 1 will the basic needs for most companies. I'm not fan of adding more complexity to a process. And if we introduce Scenario 2, it should be optional and only visible if the user sets the parameter "Approve Purchase Requests on a per-line basis" in the Config.

**Comment by pedrobaeza** [comment]
Is there something to do with this issue or can we close it?

**Comment by sbidoul** [comment]
Please keep this open. We may implement something like this soon.
