### ISSUE TITLE
[purchase_request] mutliple PR of the same product by different users

### ISSUE THREAD

**Issue by sbidoul** [OCA/purchase-workflow#275]
When several users do each a purchase request for the same product, and these requests are grouped in the same purchase order, they end up in the same purchase order line.

After that the tracking is not individualized per purchase request.

For example:
- user A does a PR for qty 1
- user B does a PR for qty 2
- both are grouped in the same RFQ line for a quantity of 3
- the field quantity in RFQ shows 3 for both users
- when receiving, the received quantity is shown in the tracker of both PR

@jbeficent @aheficent given the current data model, I understand why it is so.

Is it by design, do you consider this acceptable or is this an improvement to be considered? Any ideas on this topic?

cc/ @chrisdec @adrienpeiffer @JonathanNEMRY

**Comment by JordiBForgeFlow** [comment]
I'm aware of this. And think that it would be good to improve. Now sure how.

Wow do you decide who to notify when you receive 1 unit of the 3? User A or
user B?

**Comment by pedrobaeza** [comment]
Any news on this?
