### ISSUE TITLE
[purchase_request] Non-required field on purchase.request.line

### ISSUE THREAD

**Issue by andhit-r** [OCA/purchase-workflow#283]
Any technical reason why _name_ or _product_id_ on purchase.request.line is not required? It seems strange if user can add data without both fields.

Thanks is advance.

cc: @jbeficent @aheficent

**Comment by pedrobaeza** [comment]
Can you make a PR about this?

**Comment by andhit-r** [comment]
@pedrobaeza sure. But i'm not sure which way to go, (1) improve the original module, or (2) create new module. That's why i asked @jbeficent as original author. I need to know the technical reason behind the original module first.

**Comment by pedrobaeza** [comment]
I think it's only something he forgot. You should improve current module.

**Comment by JordiBForgeFlow** [comment]
@andhit-r Yes, please make a PR. I agree that this is needed as an improvement of the original module. What is important is that name is required, not product_id. Because many times users do not really know a product. They just express a need.
