### ISSUE TITLE
purchase_partial_invoice: purchase line removed from "Invoice control > On Purchase Order Lines" when Invoice is validated

### ISSUE THREAD

**Issue by alexis-via** [OCA/purchase-workflow#29]
I am experiencing this bug with v8, but, when looking at the code, it seems to be the same on v7. Here is the scenario to reproduce it:
1) install purchase_partial_invoice
2) Create a new PO with 1 PO line quantity 10 and set Invoicing Control = 'Based on Purchase Order lines'
3) validate the PO
4) Go to Invoice Control > On Purchase Order Lines
Select the purchase order line, start the wizard "Create Invoices" and set "Quantity to invoice" to 3 and validate
-> it creates a draft supplier invoice. If you look in "Invoice Control > On Purchase Order Lines", the purchase order line is still present (because there is still 7 items left to invoice)
5) Validate the supplier invoice
Now, if you look in "Invoice Control > On Purchase Order Lines", the purchase order line is NOT there any more... although there are still 7 items left to invoice ! That's the bug !

Code analysis:
In step 5, the purchase order line disappears because it is 'invoiced' = True. The code that writes invoice=True is in addons/purchase/purchase.py line 1470 (on v8) in the inherit of the method invoice_validate() of the object account.invoice:

self.pool['purchase.order.line'].write(cr, uid, invoiced, {'invoiced': True})

I am very surprised by that, because, for me, the module purchase_partial_invoice is not usable with this bug.

A possible solution is to inherit invoice_validate() in the module purchase_partial_invoice to re-write 'invoiced': False for the purchase order lines that are not fully invoiced.

**Comment by pedrobaeza** [comment]
It seems very similar to the one I found on sale_order_partial_invoice, that marks _invoiced_ flag that way. You can check it here if it helps:

https://github.com/OCA/account-invoicing/pull/8

**Comment by alexis-via** [comment]
I made the test with OpenERP 7: the bug is exactly the same.

According to the MP on LP https://code.launchpad.net/~elbati/purchase-wkfl/adding_purchase_partial_invoicing_7/+merge/167065 this  module was accepted for OpenERP 7. So, this would mean that this module has NEVER worked :-( I hope I am wrong...

@eLBati What's your point of view on this ?

**Comment by pedrobaeza** [comment]
When I tested, it was working fine, so I think it's a change on the core in the way invoiced flag is treated, because it happened the same with the partial invoicing in sale.

**Comment by alexis-via** [comment]
Maybe the best solution to this would be to propose this feature to the core (at least for v9). When you look at the code of the module, it's pretty simple... and the biggest part of the code of this module consist in calling super() which writes 'True' on the 'invoiced' field, and then re-writing 'False' on the 'invoiced' field ! If we want to fix this bug, we would have to do the same with the function invoice_validate(), which would imply a double loop on invoice lines (in the purchase module + in purchase_partial_invoicing, which would slow down significantly the validation of an invoice.

**Comment by eLBati** [comment]
Hello @alexis-via I think the bug was born after the commit
https://github.com/odoo/odoo/commit/a701934ac79a32cb534ff768190c1a444b2f8544

Before that, the PO lines were set to `invoiced` after invoice creation. After that commit, after invoice validation.

So, the lines

```
            if po_line.invoiced_qty != po_line.product_qty:
                po_line.write({'invoiced': False})
```

of `purchase_partial_invoicing/wizard/po_line_invoice.py`
are now unnecessary and should be moved to invoice_validate.

**Comment by JordiBForgeFlow** [comment]
Hi @alexis-via, I believe that my PR fully fixes the issue. It is in 7.0, but should be pretty simple to port it to 8.0.

**Comment by yvaucher** [comment]
I remove 7.0 tag as #91 fixed it

**Comment by adrienpeiffer** [comment]
Corrections in #91 integreted on the port #108 ! Thanks !
