### ISSUE TITLE
product_supplierinfo_discount improvment

### ISSUE THREAD

**Issue by legalsylvain** [OCA/purchase-workflow#298]
hi, 

I just saw that this great module was ported in V9.0.

I was thinking to add an extra feature on res.partner. A new field named 'global_discount', that could be the default value on the product supplier info, when created.
What do you think about such feature ? 

thanks.

CC @pedrobaeza, @JonathanNEMRY

**Comment by JonathanNEMRY** [comment]
Hello @legalsylvain 
I am not sure about the fields' name but the default value appears to me as a good idea :+1:

**Comment by legalsylvain** [comment]
Ok, thanks for your feedback ! I'll do that. What about :
- supplier_discount
- recurring_discount

regards.

**Comment by JonathanNEMRY** [comment]
`recurring_discount` sounds good to me :smiley:

**Comment by pedrobaeza** [comment]
Better to be called `default_supplierinfo_discount`. I made something similar with a default discount on sales, but making the view totally inheritable: https://github.com/OCA/partner-contact/blob/9.0/partner_default_sale_discount/models/sale_order.py#L18

**Comment by legalsylvain** [comment]
Done in recent version.
