### ISSUE TITLE
Tax computation on discounted amount in Purchase Order

### ISSUE THREAD

**Issue by arun3187** [OCA/purchase-workflow#303]
After installing the module "purchase_discount", the Discount % field is getting to Purchase Order line. However, tax computation is happening on the line amount before the discount is applied which is wrong. 

Ex:

Qty: 1
Unit Price: 100
Disc %: 10.00

Line Amount: 90
VAT 5% amount should be 4.5 instead it is calculating VAT as 5 which is on the before discount amount of 100. This needs to corrected.

Please advice if there is any solution is already available for this issue.

**Comment by pedrobaeza** [comment]
You are not indicating version.

**Comment by arun3187** [comment]
It's Odoo v8

**Comment by pedrobaeza** [comment]
I'm using it and I don't have that problem. Is VAT included in your tax?

**Comment by arun3187** [comment]
In my system, tax is computed correctly only if it added to the Purchase Order after the discount is applied. I think the function that computes the tax should be called when the discount value is changed.

**Comment by pedrobaeza** [comment]
Please try to reproduce it on runbot.

**Comment by pedrobaeza** [comment]
https://runbot.odoo-community.org/runbot/142/8.0

**Comment by arun3187** [comment]
Created a Request for Quotation  RFQ005 on runbot but not able to reproduce the error. Let me verify this at my end if there is any other module playing around this.

**Comment by gustavovalverde** [comment]
This can be closed @pedrobaeza

**Comment by pedrobaeza** [comment]
OK, thanks.
