### ISSUE TITLE
[8.0] purchase_picking_state causes openerp.osv.expression: Field 'Picking List' (picking_ids) can not be searched: non-stored function field without fnct_search

### ISSUE THREAD

**Issue by alexis-via** [OCA/purchase-workflow#331]
When I install purchase_picking_state on odoo 8, I get:
```
openerp.osv.expression: Field 'Picking List' (picking_ids) can not be searched: non-stored function field without fnct_search
```

I think it is caused by the fact that the function field picking_state is now stored but we have @api.depends('picking_ids', 'picking_ids.state') and pickings_ids on purchase.order is a non-stored function field without search, cf https://github.com/odoo/odoo/blob/8.0/addons/purchase/purchase.py#L275

The picking_state is a stored field since this commit:
https://github.com/OCA/purchase-workflow/commit/a3c2631f328c43ebb7050d749f19a218ba92d00a

**Comment by bealdav** [comment]
ping @chafique-delli

**Comment by bealdav** [comment]
as said by @alexis-via in v10 picking_ids move from o2m -> m2m

**Comment by bealdav** [comment]
see https://github.com/OCA/purchase-workflow/pull/324

**Comment by isabellerichard** [comment]
Hello,

Fixed on v9 by changing `depends` of `_compute_picking_state` with:
```@api.depends('order_line.move_ids', 'order_line.move_ids.state')```

Explanation: picking_ids is a non stored computed field, so I use directly its own `depends` to compute `picking_state`.

Hope this can help.

Regards

**Comment by chafique-delli** [comment]
@alexis-via , Fixed by PR: https://github.com/OCA/purchase-workflow/pull/354

**Comment by sebastienbeau** [comment]
Fixed https://github.com/OCA/purchase-workflow/pull/354
