### ISSUE TITLE
[8.0][9.0][purchase_request_to_rfq] transferring to PO multiple PR lines for the same product that has minimum qty

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/purchase-workflow#333]
Now, if two people purchase 1 iMac using separate purchase requests (PR1, PR2), and iMac has as a supplier Asustek, with a minimum order qty of 5, the resulting PO will be for 5 units, but only linked to PR1.

This line:
https://github.com/OCA/purchase-workflow/blob/8.0/purchase_request_to_rfq/wizard/purchase_request_line_make_purchase_order.py#L221

should be executed regardless if new_qty > po_line.product_qty. 

This issue occurs in 8.0, 9.0 and 10.0 (#287)

**Comment by LoisRForgeFlow** [comment]
in v10 this is attended here: https://github.com/OCA/purchase-workflow/pull/397
