### ISSUE TITLE
[9.0][purchase_request_to_rfq] When creating a PO line from a PR line the supplier pricelists and taxes are not determined in the PO line

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/purchase-workflow#344]
See below. The first line in the picture was created from a PR. The second line was created manually.

![image](https://cloud.githubusercontent.com/assets/7683926/23160545/38c40cda-f827-11e6-9f80-4ab4cc7feae6.png)

**Comment by JordiBForgeFlow** [comment]
@lreficent can you review?

**Comment by lreficent** [comment]
the manually created one should be the same as the other, doesn't it?

**Comment by LoisRForgeFlow** [comment]
PR created @jbeficent
