### ISSUE TITLE
[RFC] Purchase manual incoming shipment

### ISSUE THREAD

**Issue by LoisRForgeFlow** [OCA/purchase-workflow#380]
Now, when a purchase order is confirmed the incoming shipments are automatically created covering the whole PO, no more, no less.

This automation makes the shipment related to the PO inflexible and kind of useless in many scenarios. The supplier can decide to: 
send you several PO's in the same delivery, send only some PO lines, send a different amount than the specified in the PO.
or even send in a combination of this three cases that you will have to match the some PO lines.

So, We propose to create a module to unlink the confirmation of the PO's and the creation of the incoming shipments in a similar way that https://github.com/OCA/sale-workflow/pull/404 do with sales. If the supplier has the freedom to deliver as desired, we should be able to receive in a proper way.

The proposed workflow is:

#. Create PO.
#. Confirm PO.
#. Suppllier inform of an incoming shipment or the items are received into the warehouse.
#. We create the incoming shipment in our system and select the PO or PO lines covered by it.

At the end, is kind of a replication of the vendor invoices approach to add PO lines to the invoice.

Known issues
------------

* This will affect the forecasted quantity computation on products if the user do not create the incoming shipments. Maybe to modify this computation method will be interesting, in order to include the PO lines in the calculation.

* This will break some standard tests. In order to avoid this, we can make this feature optional and set as default behavior the current one, so the user has to manual activate this feature through the settings.

**Comment by quentinDupont** [comment]
Seems that it's now cover by your module https://github.com/OCA/purchase-workflow/tree/12.0/purchase_manual_delivery :slightly_smiling_face:
