### ISSUE TITLE
Propose new addons, Split RFQ and Purchase Order (as separate document)

### ISSUE THREAD

**Issue by kittiu** [OCA/purchase-workflow#386]
Hi, in addition to https://github.com/OCA/sale-workflow/issues/448

I would like to submit our frequently used module, purchase_split_quote2order.
Are there similar module already exists, and/or will this module be useful enough to be in OCA?
Here the link, now is for v8.
https://github.com/pabi2/pb2_generic/blob/master/purchase_split_quote2order

Similar to the sale-workflow, I am ready to change name to "purchase_isolated_quotation"

Thank you,

**Comment by pedrobaeza** [comment]
I think you can go ahead.
