### ISSUE TITLE
[9.0][purchase_request_procurement] Procurement not cancelled when a purchase request is cancelled

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/purchase-workflow#396]
We need to change the purchase_request_procurement module, so that cancelling a purchase request will cancel the procurement as well. But then you should NOT be able to reset the purchase request back to draft, if the related procurements are cancelled.

Also, you should not be able to cancel a procurement if a subsequent purchase request exists. The user needs to first cancel it through the procurement.

**Comment by JordiBForgeFlow** [comment]
cc @lreficent

**Comment by sbidoul** [comment]
cc/ @benwillig @gva-acsone

**Comment by LoisRForgeFlow** [comment]
This comment describes the [final approach](https://github.com/OCA/purchase-workflow/pull/398#issuecomment-303458774) followed.

**Comment by benwillig** [comment]
@lreficent @jbeficent Can I start to migrate to 10.0 merged changes ?

**Comment by JordiBForgeFlow** [comment]
@benwillig Yes, you can
