### ISSUE TITLE
[purchase_discount] missing trailing parenthesis and "digits_compute" on purchase_discount.py line 43

### ISSUE THREAD

**Issue by TheCloneMaster** [OCA/purchase-workflow#4]
Line 43 in purchase_discount.py should change from

```
    'discount': fields.float('Discount (%)', dp.get_precision('Discount'),
```

to 

```
    'discount': fields.float('Discount (%)', digits_compute=dp.get_precision('Discount')),
```

**Comment by pedrobaeza** [comment]
See #2 and #3 for the corresponding patches.

Please review it.

**Comment by TheCloneMaster** [comment]
Hi Pedro,

Thanks for your follow up.

Just one still missing on line #43....    digits_compute=
or else it will try to use given parameter as digits, that expects a
tuple...

Regards,
-Mario

**Comment by pedrobaeza** [comment]
Done! Please approve it and I'll proceed with the merge.

**Comment by guewen** [comment]
The PR are merged.
