### ISSUE TITLE
Purchase Discount Account

### ISSUE THREAD

**Issue by randyraharjo93** [OCA/purchase-workflow#413]
When you put discount on purchase line, it's good, but it doesn't have any impact on the account, We don't have account to record the value of discount. That's quite OK. But when we have the product configured with perpeptual account, the accounting value gone wrong. 

1.When we buy the product, the amount of stock account is not the discounted one. 
     For Example, we buy a $ 1,000 product with 20% discount = $ 800
2. When we sell the product, the amount it takes as the cost of revenue is the full amount rather than the discount amount.
    For Example, we sell at $ 1,000 
3. What I except is to have $ 200 profit, but I don't have it. Because the cost of revenue is $ 1,000

I don't know if it's intended / my accounting knowledge is too poor / we need to update this module... I appreciate any help.

**Comment by pedrobaeza** [comment]
You are not indicating the version. Anyway, this was patched in all versions some time ago. Update your code.

**Comment by randyraharjo93** [comment]
@pedrobaeza Thanks for replying, I'm sorry not to put the version. This is what I have in the odoo apps "Latest Version: 	10.0.9.0.1.0.0". 
What version should I get? Is there any configuration I need to do?

**Comment by pedrobaeza** [comment]
It seems that 10.0 version doesn't contain the code for the moves: https://github.com/OCA/purchase-workflow/blob/9.0/purchase_discount/models/purchase_order.py#L33.

Can you please include it and make a PR?

**Comment by randyraharjo93** [comment]
An error occured, this is what I have.

Happened when I press "confirm Sale"


>    self.price_unit *= (100 - self.discount) / 100
>   File "/home/odoo_10/odoo/odoo/fields.py", line 908, in __set__
>     record.write({self.name: write_value})
>   File "/home/odoo_10/odoo/addons/purchase/models/purchase.py", line 561, in write
>     orders._create_picking()
>   File "/home/odoo_10/odoo/addons/purchase/models/purchase.py", line 411, in _create_picking
>     moves = order.order_line._create_stock_moves(picking)
>   File "/home/odoo_10/odoo/addons/purchase/models/purchase.py", line 617, in _create_stock_moves
>     price_unit = line._get_stock_move_price_unit()
>   File "/home/odoo_10/odoo_mmr/purchase_discount/models/purchase_order.py", line 42, in _get_stock_move_price_unit
>     self.price_unit *= (100 - self.discount) / 100
>   File "/home/odoo_10/odoo/odoo/fields.py", line 908, in __set__
>     record.write({self.name: write_value})
>   File "/home/odoo_10/odoo/addons/purchase/models/purchase.py", line 561, in write
>     orders._create_picking()
>   File "/home/odoo_10/odoo/addons/purchase/models/purchase.py", line 411, in _create_picking
>     moves = order.order_line._create_stock_moves(picking)
>   File "/home/odoo_10/odoo/addons/purchase/models/purchase.py", line 617, in _create_stock_moves
>     price_unit = line._get_stock_move_price_unit()
>   File "/home/odoo_10/odoo_mmr/purchase_discount/models/purchase_order.py", line 42, in _get_stock_move_price_unit
>     self.price_unit *= (100 - self.discount) / 100
>   File "/home/odoo_10/odoo/odoo/fields.py", line 908, in __set__
>     record.write({self.name: write_value})
>   File "/home/odoo_10/odoo/addons/purchase/models/purchase.py", line 561, in write
>     orders._create_picking()
>   File "/home/odoo_10/odoo/addons/purchase/models/purchase.py", line 411, in _create_picking
>     moves = order.order_line._create_stock_moves(picking)
>   File "/home/odoo_10/odoo/addons/purchase/models/purchase.py", line 617, in _create_stock_moves
>     price_unit = line._get_stock_move_price_unit()
>   File "/home/odoo_10/odoo_mmr/purchase_discount/models/purchase_order.py", line 42, in _get_stock_move_price_unit
>     self.price_unit *= (100 - self.discount) / 100
>   File "/home/odoo_10/odoo/odoo/fields.py", line 908, in __set__
>     record.write({self.name: write_value})
>   File "/home/odoo_10/odoo/addons/purchase/models/purchase.py", line 561, in write
>     orders._create_picking()
>   File "/home/odoo_10/odoo/addons/purchase/models/purchase.py", line 411, in _create_picking
>     moves = order.order_line._create_stock_moves(picking)
>   File "/home/odoo_10/odoo/addons/purchase/models/purchase.py", line 617, in _create_stock_moves
>     price_unit = line._get_stock_move_price_unit()
>   File "/home/odoo_10/odoo_mmr/purchase_discount/models/purchase_order.py", line 42, in _get_stock_move_price_unit
>     self.price_unit *= (100 - self.discount) / 100
>   File "/home/odoo_10/odoo/odoo/fields.py", line 908, in __set__
>     record.write({self.name: write_value})
>   File "/home/odoo_10/odoo/addons/purchase/models/purchase.py", line 561, in write
>     orders._create_picking()
>   File "/home/odoo_10/odoo/addons/purchase/models/purchase.py", line 411, in _create_picking
>     moves = order.order_line._create_stock_moves(picking)
>   File "/home/odoo_10/odoo/addons/purchase/models/purchase.py", line 617, in _create_stock_moves
>     price_unit = line._get_stock_move_price_unit()
>   File "/home/odoo_10/odoo_mmr/purchase_discount/models/purchase_order.py", line 42, in _get_stock_move_price_unit
>     self.price_unit *= (100 - self.discount) / 100
>   File "/home/odoo_10/odoo/odoo/fields.py", line 908, in __set__
>     record.write({self.name: write_value})
>   File "/home/odoo_10/odoo/addons/purchase/models/purchase.py", line 561, in write
>     orders._create_picking()
>   File "/home/odoo_10/odoo/addons/purchase/models/purchase.py", line 408, in _create_picking
>     picking = StockPicking.create(res)
>   File "/home/odoo_10/odoo/addons/stock/models/stock_picking.py", line 415, in create
>     return super(Picking, self).create(vals)
>   File "/home/odoo_10/odoo/addons/mail/models/mail_thread.py", line 228, in create
>     thread = super(MailThread, self).create(values)
>   File "/home/odoo_10/odoo/odoo/models.py", line 3816, in create
>     record = self.browse(self._create(old_vals))
>   File "/home/odoo_10/odoo/odoo/models.py", line 3978, in _create
>     self.recompute()
>   File "/home/odoo_10/odoo/odoo/models.py", line 5292, in recompute
>     vals = rec._convert_to_write({n: rec[n] for n in ns})
>   File "/home/odoo_10/odoo/odoo/models.py", line 5292, in <dictcomp>
>     vals = rec._convert_to_write({n: rec[n] for n in ns})
>   File "/home/odoo_10/odoo/odoo/models.py", line 5191, in __getitem__
>     return self._fields[key].__get__(self, type(self))
>   File "/home/odoo_10/odoo/odoo/fields.py", line 869, in __get__
>     self.determine_value(record)
>   File "/home/odoo_10/odoo/odoo/fields.py", line 955, in determine_value
>     self.compute_value(recs)
>   File "/home/odoo_10/odoo/odoo/fields.py", line 935, in compute_value
>     self._compute_value(records)
>   File "/home/odoo_10/odoo/odoo/fields.py", line 926, in _compute_value
>     getattr(records, self.compute)()
>   File "<string>", line 2, in _compute_dates
>   File "/home/odoo_10/odoo/odoo/api.py", line 361, in loop
>     result = [method(rec, *args, **kwargs) for rec in self]
>   File "/home/odoo_10/odoo/addons/stock/models/stock_picking.py", line 344, in _compute_dates
>     self.min_date = min(self.move_lines.mapped('date_expected') or [False])
>   File "/home/odoo_10/odoo/odoo/fields.py", line 869, in __get__
>     self.determine_value(record)
>   File "/home/odoo_10/odoo/odoo/fields.py", line 971, in determine_value
>     record._prefetch_field(self)
>   File "/home/odoo_10/odoo/odoo/models.py", line 3061, in _prefetch_field
>     result = records.read([f.name for f in fs], load='_classic_write')
>   File "/home/odoo_10/odoo/odoo/models.py", line 3001, in read
>     self._read_from_database(stored, inherited)
>   File "/home/odoo_10/odoo/odoo/models.py", line 3155, in _read_from_database
>     field.read(fetched)
>   File "/home/odoo_10/odoo/odoo/fields.py", line 2152, in read
>     lines = comodel.search(domain, limit=self.limit)
>   File "/home/odoo_10/odoo/odoo/models.py", line 1509, in search
>     res = self._search(args, offset=offset, limit=limit, order=order, count=count)
>   File "/home/odoo_10/odoo/odoo/models.py", line 4205, in _search
>     query = self._where_calc(args)
>   File "/home/odoo_10/odoo/odoo/models.py", line 4004, in _where_calc
>     e = expression.expression(domain, self)
>   File "/home/odoo_10/odoo/odoo/osv/expression.py", line 635, in __init__
>     self._unaccent = get_unaccent_wrapper(model._cr)
>   File "/home/odoo_10/odoo/odoo/osv/expression.py", line 430, in get_unaccent_wrapper
>     if odoo.registry(cr.dbname).has_unaccent:
>   File "/home/odoo_10/odoo/odoo/__init__.py", line 52, in registry
>     return modules.registry.Registry(database_name)
>   File "/home/odoo_10/odoo/odoo/modules/registry.py", line 53, in __new__
>     return cls.registries[db_name]
>   File "/home/odoo_10/odoo/odoo/tools/func.py", line 68, in wrapper
>     return func(self, *args, **kwargs)
>   File "/home/odoo_10/odoo/odoo/tools/lru.py", line 44, in __getitem__
>     self[a[0]] = a[1]
>   File "/home/odoo_10/odoo/odoo/tools/func.py", line 70, in wrapper
>     lock.release()
> RuntimeError: maximum recursion depth exceeded
