### ISSUE TITLE
[9.0][purchase_discount] on a purchase invoice in draft total is not updated when quantity change

### ISSUE THREAD

**Issue by admin-odoo-supercoop** [OCA/purchase-workflow#434]
Odoo 9.0.

Since we install the **purchase_discount** module, we observe a change in the _account.invoice.line_: the total field was updated when the quantity changed, but no more. We have to save the invoice to see the total updated.
When we uninstalled the purchase_discount module, the issue is fixed.

<img width="1206" alt="purchase_invoice" src="https://user-images.githubusercontent.com/24719117/28419143-6e53698e-6d5e-11e7-9c36-4a12e58cc4f5.png">

Also when creating the invoice from the Purchase Order, all fields are set except quantity and price (set to 0 instead of Purchase Order values). Here is a screenshot:

<img width="975" alt="capture d ecran 2017-07-20 a 16 57 56" src="https://user-images.githubusercontent.com/24719117/28424056-f503030a-6d6c-11e7-83ca-0b21628cc93f.png">

**Comment by pedrobaeza** [comment]
Please try on latest builds.
