### ISSUE TITLE
unknown field in domain "account_type" in "purhcase_request" module

### ISSUE THREAD

**Issue by yk2kus** [OCA/purchase-workflow#457]
https://github.com/OCA/purchase-workflow/blob/10.0/purchase_request/views/purchase_request_view.xml#L104

in which module this field is created? getting error on opening analytic account.

**Comment by pedrobaeza** [comment]
It's an old remnant of v8 accounting structure I think.

**Comment by JordiBForgeFlow** [comment]
@aheficent can you fix that?

**Comment by JordiBForgeFlow** [comment]
See the proposed PR

**Comment by yk2kus** [comment]
https://github.com/OCA/purchase-workflow/pull/458

**Comment by bodedra** [comment]
Good to close.
