### ISSUE TITLE
[11.0] merge "purchase_fop_shipping" and "purchase_minimum_amount"

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/purchase-workflow#464]
We have identified that in v10 the following modules provide very similar features:
purchase_fop_shipping: https://github.com/OCA/purchase-workflow/tree/10.0/purchase_fop_shipping
purchase_minimum_amount: https://github.com/OCA/purchase-workflow/tree/10.0/purchase_minimum_amount

As we are now planning to migrate purchase_minimum_amount to v11, we propose to merge them together. We can prepare a migration script for those using purchase_fop_shipping.

**Comment by JordiBForgeFlow** [comment]
cc @mourad-ehm @bealdav what do you think?

**Comment by mourad-ehm** [comment]
I think is a good idea to merge them.  
What to you think if the new module will be based on base_exception (like sale_exception) ? 
I can study to possibility to migrate base_exception to v 11 if you use it.

**Comment by bealdav** [comment]
@jbeficent do you consider to develop purchase_exception (sale_exception like)) ? Then purchase_fop_shipping and purchase_minimum_amount could be merged in a very small module just two use cases of exceptions ?
If yes, I'm OK with mourad proposal to migrate base_exception in v11 even if we have no project in v11 for now.

**Comment by JordiBForgeFlow** [comment]
@bealdav `purchase_fop_shipping` does what `purchase_minimum_amount` does, but slightly differently in the way to approach. 

Also fyi, 'purchase_order_approval_block' has also been merged recently. https://github.com/OCA/purchase-workflow/tree/10.0/purchase_order_approval_block and `purchase_minimum_amount` depends on it.

We could keep the approval block field proposed in `purchase_minimum_amount`, if the amount is below the minimum, and then raise an exception when a user attempts to confirm an order, not because the amount is lower, but because the order has an approval block set.

Another interesting thing is that in `purchase_minimum_amount` we rely on the existing PO status 'To Approve'. The standard validation of amount >  whatever defined in company, relies on this status.

To me, you should define in the exception rules if you want the PO to change to 'To Approve' when this exception occurs. This would be a useful mechanism of the PO approvers to review certain exception rules.

For example
* Rule A says when the amount is less than minimum set by the vendor, it requires the approval by a purchase manager.
* Rule B says that if the partner does not have a zip code, it requires inmediate correction (the PO stays in draft).

**Comment by bealdav** [comment]
OK, I'll let @mourad-ehm talk with you here, but on our side as indicated, we can port base_exception in v11 and bring some modifications related triggering exceptions : as far as I remember in sale_exception it's when the sale `is confirmed`. But it could be to any specified step of the status. 
Thanks.

**Comment by mourad-ehm** [comment]
Ok, I will add a field next_state to the rule. Thus if the state is set, we change the object value to this state if the rule is detected. If no state is set on rule, we only block until the correction is set or the action is forced by a user which belong to the group "group_exception_rule_manager".

**Comment by mourad-ehm** [comment]
I migrate base_exception https://github.com/OCA/server-tools/pull/1025. I will create purchase exception module.

**Comment by mourad-ehm** [comment]
I added a new module purchase_exception: https://github.com/OCA/purchase-workflow/pull/467
