### ISSUE TITLE
[RFC] purchase request 11.0

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/purchase-workflow#465]
We want to start migrating the purchase request modules to 11.0. I would like to gather ideas for improvements from people who have been using this feature (since 7.0), so that we can improve.

To discuss:
* [ ] Quantity purchased / quantity pending to purchase, for each line. 
* [ ] Ability to search for purchase request & lines with qty pending to purchase
* [x] Add done status https://github.com/OCA/purchase-workflow/pull/385 
* [ ] merge 'purchase_request', 'purchase_request_to_rfq', 'purchase_request_procurement'
* [ ] with procurement.order gone, what do we do with purchase_request_to_procurement? Perhaps create a separate model 'procurement.request'?

**Comment by HviorForgeFlow** [comment]
WIP #544

**Comment by pedrobaeza** [comment]
Closing as there's PR
