### ISSUE TITLE
10.0 branch is broken

### ISSUE THREAD

**Issue by MiquelRForgeFlow** [OCA/purchase-workflow#469]
![selection_022](https://user-images.githubusercontent.com/25005517/31731625-f17d0fea-b435-11e7-8643-9251a3e93038.png)

Can somebody fix it? It seems it fails in `purchase_discount` and `purchase_triple_discount` tests, and maybe the commit https://github.com/OCA/purchase-workflow/commit/1b736733615564a78cdfe0eb224d423f7664c36b is the culprit :smirk:

cc: @pedrobaeza

**Comment by pedrobaeza** [comment]
No, it's the contrary... that commit solves an issue. Any way, I'll check it.

**Comment by pedrobaeza** [comment]
The culprit is https://github.com/odoo/odoo/commit/5afb5ecd04cf49be6bedb655b187b19a65e1e02d#diff-3bf7fa37ad269bad5d8df8214bd5206b

Fixed in https://github.com/OCA/purchase-workflow/commit/e6a85a0e7f1de02540a41cc35c0e7f9516c4fe3a
