### ISSUE TITLE
subcontracted_service: no rule has been determined

### ISSUE THREAD

**Issue by ccandito** [OCA/purchase-workflow#472]
Dear All,
I've created a service product setting the indicator "subcontracting service".
I've also created a procurement order for that service. Unfortunately the rule "Subcontracting Service" is  not determined so it has to be entered manually.
Is it the right behaviour?
Regards
claudio candito

**Comment by LoisRForgeFlow** [comment]
Hi @ccandito 

I just reproduce the steps [here](https://github.com/OCA/purchase-workflow/blob/9.0/subcontracted_service/README.rst) on v9 runbot and it worked as expected for me.

**Comment by LoisRForgeFlow** [comment]
attaching a picture of the procurement:
![image](https://user-images.githubusercontent.com/23449160/31932025-58eed38e-b8a5-11e7-9655-fa11459faf05.png)

**Comment by ccandito** [comment]
thanks a lot
claudio
