### ISSUE TITLE
'purchase.order' object has no attribute '_columns'

### ISSUE THREAD

**Issue by atlaskong** [OCA/purchase-workflow#491]
When I entered "purchase request" menu, it show "'purchase.order' object has no attribute '_columns'".

And I can not enter.

What should I do now？

Help me, please.

**Comment by pedrobaeza** [comment]
Please try on runbot.

You haven't specified installed module and version any way.

**Comment by pedrobaeza** [comment]
No answer, so I close.

**Comment by atlaskong** [comment]
Dear Sir,

I see your mail today.
Sorry for late.
Thank you for your help.

Regards,
Atlas

2018-03-29 22:02 GMT+08:00 Pedro M. Baeza <notifications@github.com>:
