### ISSUE TITLE
Will the Purchase line discounts reflect in Vendor bills?

### ISSUE THREAD

**Issue by balagopalr22** [OCA/purchase-workflow#495]
I have given purchase line discounts for some products. But when i create Vendor bill against that order, the discounts are not reflecting.

**Comment by pedrobaeza** [comment]
Version?

**Comment by balagopalr22** [comment]
V10

**Comment by bodedra** [comment]
@balagopalr22 I can not able to reproduce same. IMO here you may find reference https://github.com/OCA/purchase-workflow/blob/10.0/purchase_discount/models/account_invoice.py#L10 of code, which will pass discount from purchase order line to invoice line.

@pedrobaeza we can close these issue.
