### ISSUE TITLE
[purchase_location_by_line] : module is not allowing to add extra PO lines once PO is processed

### ISSUE THREAD

**Issue by bista-amitd** [OCA/purchase-workflow#498]
To Reproduce:
1). Create one Purchase Order
2). Add one line on it
3). Confirm the purchase order, process the picking
4). Now try to add a new line and save, it's giving following warning:
'Quantities, Units of Measure, Products and Locations cannot be modified on stock moves that have already been processed (except by the Administrator).'

It's trying to write the location on processed stock move which is the processed product, it should write the location on newly created line only.

**Comment by MiquelRForgeFlow** [comment]
This issue can be closed.
