### ISSUE TITLE
stock_landed_cost_company_percentage

### ISSUE THREAD

**Issue by max3903** [OCA/purchase-workflow#505]
# Module description

This module allows you to add a fixed percentage of landed costs to every received items.

# Configuration

* Go to Inventory > Master Data > Products
* Create landed cost product. Make sure the landed cost box is checked.
* Go to Settings > Company
* Select a company and go to the Accounting tab
* Select or create a journal for the landed costs accounting entries
* Add landed costs by selecting the landed cost product and entering the percentage

# Usage

* Go to Purchases > Purchase > Requests for Quotation
* Select or create a new one
* Confirm the order and receive the products
* Go to Inventory > Operations > Landed Costs
* A new landed cost has been created for the receipt you just processed. The value has been calculated based on the percentage and the total cost of the received products.

**Comment by max3903** [comment]
Ping @bodedra

**Comment by pedrobaeza** [comment]
Can be closed as the PR is merged.
