### ISSUE TITLE
Module `purchase_delivery_split_date` need compatible with Odoo 11.0

### ISSUE THREAD

**Issue by hizbul-evl** [OCA/purchase-workflow#509]
`purchase_delivery_split_date` is showing error with python3 

> purchase_delivery_split_date/models/purchase.py", line 49, in _create_stock_moves
>     key=lambda l: sorted(self._get_group_keys(
> TypeError: unorderable types: dict() < dict()
>

**Comment by pedrobaeza** [comment]
Module is not yet migrated to v11.
