### ISSUE TITLE
[10.0][purchase_request] product price not displayed

### ISSUE THREAD

**Issue by remz1337** [OCA/purchase-workflow#515]
This is an enhancement to the module.

It doesn't make sense that the approver doesn't see the price of the items requested. There are 2 cases:
1) The product is a one time purchase, so it doesn't exist in the system. Then only the description is filled but there should be a way to indicate estimated/market price (user can put reference in the chatter if necessary)

2) The product exists in the system and is frequently bought from the same vendor at a fixed price. In a regular PO, the price would appear correctly, the purchase request should act similarly.

Right now we have to write all the prices either in the description field of the purchase request or in the chatter, and most of the time users forget to write it.

**Comment by LoisRForgeFlow** [comment]
@remz1337 It would be a good improvement, feel free to open a PR adding the feature.
