### ISSUE TITLE
[10.0][purchase_request_to_rfq] RFQ currency and payment terms do not take supplier configuration

### ISSUE THREAD

**Issue by remz1337** [OCA/purchase-workflow#524]
When I convert purchase request lines into a RFQ, the currency is always the default currency of the company instead of the currency of the supplier. Also, the payment terms is empty instead of using the payment terms of the supplier.

When I create a RFQ manually, the currency and payment terms are updated when I change the supplier. Behaviour should be the same when creating a RFQ from a Purchase Request.

**Comment by LoisRForgeFlow** [comment]
@remz1337 Yes, better to match RFQ behavior, I'd be glad to review a PR fixing this.
