### ISSUE TITLE
[10] 	purchase_triple_discount

### ISSUE THREAD

**Issue by ghost** [OCA/purchase-workflow#527]
Hello!
I have seen a strange behaviour with this module. If I apply some discount (one, two or three) the taxes are applied over the unit price. It should be over the subtotal amount, shouldnt´t it?
Thanks
![01](https://user-images.githubusercontent.com/25029267/37643760-dddf796e-2c21-11e8-9250-e3c76f051492.png)

**Comment by pedrobaeza** [comment]
Please update to latest version
