### ISSUE TITLE
[11.0] New module purchase_invoice_lines

### ISSUE THREAD

**Issue by pmartineznetquest** [OCA/purchase-workflow#538]
Hi all!

As far as we know, there is no standard way nor module to implement the purchase invoicing in the following scenarios: 

- Invoice lines from a PO separately. There is a workaround, that is to invoice from the PO and remove lines that are not going to be invoiced. 
- Invoice lines from different PO. We haven't found a native way to to that as it was implemented in previous versions.

We think that these are very common use cases and we think it'll be very useful for a lot of companies. We are ready to develop a module with the same behaviour of previous versions. This is an approach: 

- Create a list of PO lines to be invoiced (pending PO lines)
- Create a method to invoice the PO lines
    - Creating one invoice per supplier
    - Marking the lines as invoiced
    - Marking the PO as invoiced if all lines are invoiced

What do you think about this implementation? Do you know any way to natively do that or do you think is a good idea to develop it with the same behaviour of v7-8?

Thanks in advance,
Pere

CC: @svazquezco

**Comment by pedrobaeza** [comment]
Hi @pmartineznetquest 

Yeah, it can be interesting. Standard doesn't cover this, but I suggest you to use standard onchange method for performing what you want, and later remove the lines that are not marked for invoicing.

Another suggestion is to put this on OCA/account-invoicing instead with the name `purchase_line_invoicing`.
