### ISSUE TITLE
[11]Subcontracted Service install error

### ISSUE THREAD

**Issue by Moto017** [OCA/purchase-workflow#551]
The operation cannot be completed, probably due to the following:
- deletion: you may be trying to delete a record while other records still reference it
- creation/update: a mandatory field is not correctly set

[object with reference: picking_type_id - picking.type.id]

**Comment by pedrobaeza** [comment]
Please put the detailed steps to reproduce the error.

**Comment by Moto017** [comment]
Using 11 CE. Attempting app install gives the above error.

**Comment by pedrobaeza** [comment]
Which module?

**Comment by Moto017** [comment]
subcontracted_service

**Comment by pedrobaeza** [comment]
@hveficent can you check?

**Comment by HviorForgeFlow** [comment]
Yes, I could reproduce your error. Main problem is on init hook that creates a procurement rule in main company warehouse. If there is no buy stock_picking_type associated to this warehouse, installation raises this error.
I'm not so sure how to solve this problem aiming in standarization. Should I remove init_hook, or just prompt a message if stock_pciking_type is not found?
cc. @jbeficent @lreficent

**Comment by HviorForgeFlow** [comment]
@Moto017 I would like you to explain a little bit better your use case of this module, it would help to improve it, thanks.

**Comment by Moto017** [comment]
@hveficent O course.  
We subcontract portions of manufacturing with a mix of material supplied by us and supplied by subcontractor.  Our best use to handle inventory levels is with BOM's, therefore, there is no direct link to our vendor bills.  Creation of the PO by service will then verify and match production quantities and amounts.  Hope this is helpful!

**Comment by HviorForgeFlow** [comment]
I was asking about routes, if you are using multiple warehouses, among other customization, because I don't understand how you don't provide Odoo inventory with an incoming route in main company.

**Comment by Moto017** [comment]
We are using multi company as well as multiple warehouses.  We do have an incoming route in main company under Buy.  Perhaps it is a multi-company error as I noticed these are not defined in procurements.  Your commit has allowed installation and will check use.
