### ISSUE TITLE
[10.0][purchase_request_to_rfq] some French translations are negated

### ISSUE THREAD

**Issue by remz1337** [OCA/purchase-workflow#556]
Some email messages in french say the opposite of the original english message.

Install purchase_request and purchase_request_to_rfq modules from OCA repo
create a PR, convert to RFQ, then PO and receive the PO.

When the items are received, the followers of the purchase request get an email saying what was received. The message in english is right (it says the items were received) but the message in french is saying the items were NOT received (in french: "n'ont pas été reçu", should be: "ont été reçu").

**Comment by pedrobaeza** [comment]
Please fix translations on Transifex: https://odoo-community.org/page/translate
