### ISSUE TITLE
[Odoo Server Error] ValueError: Invalid field u'qty_to_receive' in leaf "<osv.ExtendedLeaf: (u'qty_to_receive', u'>', 0) on purchase_order (ctx: )>"

### ISSUE THREAD

**Issue by putao615** [OCA/purchase-workflow#561]
Once I have uninstalled the module "Purchase open qty", then click Menu "Purchases-->Purchase-->Purchase Orders",  the below issue will happened.
========================================================
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 642, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 334, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 327, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 942, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 834, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 856, in do_search_read
    offset=offset or 0, limit=limit or False, order=sort or False)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 4700, in search_read
    records = self.search(domain or [], offset=offset, limit=limit, order=order)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 1516, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 4242, in _search
    query = self._where_calc(args)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 4041, in _where_calc
    e = expression.expression(domain, self)
  File "/usr/lib/python2.7/dist-packages/odoo/osv/expression.py", line 643, in __init__
    self.parse()
  File "/usr/lib/python2.7/dist-packages/odoo/osv/expression.py", line 821, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field u'qty_to_receive' in leaf "<osv.ExtendedLeaf: (u'qty_to_receive', u'>', 0) on purchase_order (ctx: )>"

**Comment by AaronHForgeFlow** [comment]
Can you provide more info here? Which Odoo version? Can you reproduce this error on runbot? What modules form this repo are you using? How did you bump into this error?

**Comment by putao615** [comment]
the Odoo version is 10.0-20180523 (Community Edition) , sorry for I don't know runbot, but I can provide you a test environment if you need, please give me your email then I will send them to you.

**Comment by AaronHForgeFlow** [comment]
If you can reproduce the error here: http://3331816-10-0-75fda1.runbot1.odoo-community.org/web/login then we can figure it out if there's a problem. Can you check?

**Comment by putao615** [comment]
I tried many time to create a database with name "putao615_test" or "openerp_putao615", system show me database is existed but not display, could please tell me how to create or restore a database?

**Comment by AaronHForgeFlow** [comment]
I think you cannot create a database on runbot. you don't need that anyway. All OCA/purchase-workflow modules v10 are installed in that runbot so you just have to go inside and play with it :)

**Comment by putao615** [comment]
what is the username and password? I can not access it.

**Comment by putao615** [comment]
I found username and password, thanks. now I will try to reproduce the error.

**Comment by putao615** [comment]
I am lucky, now I reproduced the error again on runbot.
the step is "Purchases"-->"Purchase"-->"Purchase Orders"-->"New", the error will show immediately.
![error](https://user-images.githubusercontent.com/31801395/42331909-3d0d7e00-80a9-11e8-859f-c9f76996a575.png)

**Comment by AaronHForgeFlow** [comment]
I can create a PO without any problem, what runbot did you use?

![gifrecord_2018-07-06_113005](https://user-images.githubusercontent.com/19620251/42371615-408b2516-8110-11e8-8991-da9917a3eea8.gif)

**Comment by putao615** [comment]
try to install this module, create a purchase order, then remove this module again, create PO, error occur

**Comment by AaronHForgeFlow** [comment]
which module?

**Comment by putao615** [comment]
Purchase open qty.

**Comment by AaronHForgeFlow** [comment]
If you install the module again it does not fail.  Probably an uninstall hook is necessary.

**Comment by putao615** [comment]
what is the uninstall hook? because of uninstall problem, I can not migrate my database to another odoo system that without module "Purchase Open Qty".

**Comment by AaronHForgeFlow** [comment]
If this is only for migrating, you have to create a custom script to delete the obsolete data.

**Comment by putao615** [comment]
sorry for I don't know how to write this custom script because I am not a IT guy. but I think the module should remove related data once it be uninstalled. the reason is that all data can be calculated if need.
