### ISSUE TITLE
[11.0] purchase_discount: Stock moves created with unit_price before discount

### ISSUE THREAD

**Issue by gustavovalverde** [OCA/purchase-workflow#562]
The module is doing the right thing using `_get_stock_move_price_unit()` from the purchase order: https://github.com/odoo/odoo/blob/f6b3247c31ee176944a060afb911021d071d8a32/addons/purchase/models/purchase.py#L682

But there's also `_get_price_unit()` https://github.com/odoo/odoo/blob/ab5fcb29650349fa641c6130bf6dcbdc1ec28a07/addons/purchase/models/stock.py#L37 which makes things a bit confusing on which approach to take, because right now the stocks moves are being created with the price used by `_get_price_unit()`

A solution might be to apply the same logic from https://github.com/OCA/purchase-workflow/blob/11.0/purchase_discount/models/purchase_order.py#L51 to `_get_price_unit()` 

Right now, the bigger the discount the bigger the error on the cost when using Perpetual accounting.

Fixing this might close:
https://github.com/OCA/purchase-workflow/issues/413

**Comment by CasVissers-360ERP** [comment]
I can confirm this bug. @gustavovalverde Did you already find time to create a fix?

**Comment by gustavovalverde** [comment]
As a follow-up on the fix. This is still not working with FIFO valuation. cc: @pedrobaeza

**Comment by pedrobaeza** [comment]
I already put 90ca5317705b711aa75932df99c0f581a40db218 for that, but if you are not more explicit or give some insights... I'm not using FIFO.

**Comment by gustavovalverde** [comment]
Yes, I meant that after applying 90ca531 I got the same result, the stock move being recorded with the price before the discount (not after). I tested with AVCO and it works alright with 90ca531, but it doesn't if FIFO is being used.

**Comment by pedrobaeza** [comment]
OK, but then we need more insights, as the method executed in FIFO should be other than the referred in this issue.

**Comment by gustavovalverde** [comment]
Oh, ok my bad. I thought of functional insight. I'll debug and let you know.
