### ISSUE TITLE
[11.0] Subcontract Service Not working

### ISSUE THREAD

**Issue by randyraharjo93** [OCA/purchase-workflow#565]
How to Reproduce (use odoo demo data)

1. Set Product as External Audit as service - subcontracted service
2. On purchase tab, create a new Vendors Pricelist at asustek with price 160
3. Make a sale order to agrolait, with 1 external audit price 180
4. Confirm SO, run procurement at scheduled action

Expected Result
1. Create a new line on PO 6 external Audit

Current Result
1. Datacard purchase order line qty are increased and total increase are 160

**Comment by HviorForgeFlow** [comment]
Hi @randyraharjo93 , 
I would like helping to solve your problem, but I don't get you on:

> Current Result 
> 1. Datacard purchase order line qty are increased and total increase are 160

Could you upload some images?? Thanks,

**Comment by randyraharjo93** [comment]
Hello, thanks for the quick response

1. This is the product subcontract service
![screenshot from 2018-07-20 21 51 50](https://user-images.githubusercontent.com/17263218/43009542-2f77b1f0-8c68-11e8-9971-ac2c95a02bba.png)
2. This is the vendor / Pricelist
![screenshot from 2018-07-20 21 52 00](https://user-images.githubusercontent.com/17263218/43009579-423bc6c8-8c68-11e8-83bc-0ff13fc9b32b.png)
3. This is the Sale Order
![screenshot from 2018-07-20 21 53 11](https://user-images.githubusercontent.com/17263218/43009595-5136dc44-8c68-11e8-9e90-16d6cfd31cfc.png)
4. And this is the RFQ number 6 before running the procurement schedule
![screenshot from 2018-07-20 21 53 37](https://user-images.githubusercontent.com/17263218/43009656-70d7065a-8c68-11e8-91a5-02981f87d8f3.png)
5. And this is after running schedule
![screenshot from 2018-07-20 22 01 30](https://user-images.githubusercontent.com/17263218/43009690-89cc3dce-8c68-11e8-9c15-9a52c16855af.png)

I also record a video on how I did it.
https://drive.google.com/file/d/1BWdSlF4Ej6J7klxikUcQdNJMry4BL4JX/view

**Comment by HviorForgeFlow** [comment]
This module is a base module, by itself, it is not doing anything as description provides. 

It would be necessary to develop a module, maybe in sale-workflow, maybe called sale_order_service, overriding _action_confirm method from sale.order module, to achieve desired behavior.

Some work has been done for manufacturing orders [mrp_production_service](https://github.com/OCA/manufacture/tree/11.0/mrp_production_service).

I hope it would be helpful :)

**Comment by randyraharjo93** [comment]
Thanks, now I understand.

But why does the PO 6 number is increased each time the scheduler is working?

**Comment by HviorForgeFlow** [comment]
That product has a MIN-MAX order point, so every time you run the scheduler you don't confirm any arrival of that product and re run scheduler, how Odoo doesn't find that product in your inventory, the order points is triggered and increase the quantity in that purchase order that hasn't been validated, yet.

**Comment by HviorForgeFlow** [comment]
As the error is not related with this module, please close this issue.

**Comment by randyraharjo93** [comment]
Big thanks.
