### ISSUE TITLE
[10.0][purchase_picking_state][group_by picking_state]

### ISSUE THREAD

**Issue by EvvFoxy** [OCA/purchase-workflow#576]
Version 10.0
Module purchase_picking_state

Description:
The user would like to have a quick view on which POs have deliveries waiting to be done.

Current behaviour:
- not allowed to filter on picking_state field
- not allowed to sort on picking_state field
- not allowed to group by picking_state field

Expected behaviour:
- be able to filter on picking_state field
- be able to sort on picking_state field
- be able to group by picking_state field

**Comment by bealdav** [comment]
@EvvFoxy you're right.

Not easy to use because of non stored picking_state field

A better inspiration could be there https://github.com/akretion/ak-odoo-incubator/tree/10-sale_picking_state/sale_picking_state

with similar feature but a better implementation : stored field

**Comment by bealdav** [comment]
If a customer want to pay for that (not yet required by our customers), 
Akretion can do the job in oca
