### ISSUE TITLE
[RFC] custom uom conversion factor per product

### ISSUE THREAD

**Issue by sbidoul** [OCA/purchase-workflow#579]
# Use case

Purchase in a given unit, manage stock in another unit of a different category, where the conversion depends on the product

Example:
* purchase plastic film in tons, manage stock in square meter (weight per sqm depending on the product)
* purchase in tons, manage in liters (density depending on the product)

# proposed implementation

* module `purchase_per_product_uom_factor`
* add a new field on product: `uom_po_factor` to convert from `uom_po_id` to `uom_id`
* if that field is set, do not enforce the [constraint that uom must be in same category](https://github.com/odoo/odoo/blob/3c0a0261bed4c500cf47e049e0a58c7bef616886/addons/product/models/product_template.py#L280-L284)
* override `PurchaseOrderLine.prepare_stock_move()` to add a tuple `(uom_po, uom, uom_po_factor)` in context, if the factor is set
* in `product_uom._compute_quantity()` use the factor from the context if present

Any thoughts about the idea, existing implementation, module name, git repo, proposed implementation?

**Comment by sbidoul** [comment]
cc/ @chrisdec @gva-acsone

**Comment by pedrobaeza** [comment]
@anajuaristi @oihane you are working on something similar, isn't it?

**Comment by oihane** [comment]
@sbidoul check this out https://github.com/avanzosc/odoo-addons/pull/634 and feel free to comment

**Comment by sbidoul** [comment]
@oihane thanks a lot for the pointer. It is WIP, right (uop_coeff is not used yet in the code)?

For my use cases described above, I think we don't need a secondary purchase unit, as all we need on top of the standard is customize the uom_po/uom conversion factor on a per product basis.

**Comment by legalsylvain** [comment]
Looks very interesting. Please ping me where there are some PR to review.
kind regards.
