### ISSUE TITLE
[11.0] Request for adding Dutch translations to purchase_discount module

### ISSUE THREAD

**Issue by JordyBlankestijn** [OCA/purchase-workflow#580]
Sorry up front if i stated this issue wrong, but it is my first time doing this.

I would like to add my Dutch translations to the purchase_discount module.

Any help doing so and showing me the correct workflow is highly appreciated.

Kind regards

**Comment by pedrobaeza** [comment]
You have to use http://translation.odoo-community.org/ for that. Follow https://odoo-community.org/blog/our-blog-1/post/translations-platform-81.

**Comment by JordyBlankestijn** [comment]
Thank you Sir.
