### ISSUE TITLE
[RFC] refactoring discounts OCA modules

### ISSUE THREAD

**Issue by legalsylvain** [OCA/purchase-workflow#623]
Hi @all, 

At my company, I'm using discount features on purchase.order.
For the time being, just for the purchase part, I have to install 4 modules : 
1. ``purchase_discount`` (OCA head version 11.0 https://github.com/OCA/purchase-workflow/tree/11.0/purchase_discount)
2. ``purchase_supplierinfo_discount`` (OCA head version 11.0 https://github.com/OCA/purchase-workflow/tree/11.0/product_supplierinfo_discount)
3. ``purchase_triple_discount`` (OCA head version 10.0 https://github.com/OCA/purchase-workflow/tree/10.0/purchase_triple_discount)
4. ``purchase_supplierinfo_triple_discount`` (grap head version 8.0 https://github.com/grap/grap-odoo-incubator/tree/8.0/product_supplierinfo_triple_discount)

Basically,

- ``purchase_discount`` and ``purchase_triple_discount`` add fields on ``purchase.order`` models.
- ``purchase_supplierinfo_discount`` and ``purchase_supplierinfo__triple_discount`` add fields on ``product.supplierinfo`` models.

I don't see any use case, when user want to have a module with fields on  ``purchase.order``, without the fields on ``purchase.supplierinfo`` models. So, to simplify, I propose to merge ``purchase_supplierinfo_discount`` feature into ``purchase_discount`` module (and the same for the modules "triple" that handles discount 2 and 3.)
It will make migration through new version more easy.
I propose to make that refactoring on 12.0, as no modules has been ported for the time being.

What do you think ?

CC : modules contributors : @pedrobaeza, @cubells, @JonathanNEMRY, @StefanRijnhart, @chienandalu

**Comment by pedrobaeza** [comment]
OK for me, as dependencies doesn't change, but there's already a migration ongoing in #608

**Comment by pedrobaeza** [comment]
Can this be closed, @legalsylvain ?
