### ISSUE TITLE
[11.0] Purchase discount reapplied on product receive

### ISSUE THREAD

**Issue by altoch** [OCA/purchase-workflow#631]
module: purchase_discount
version: 11.0

· Steps to reproduce
Install the module on a clean instance of odoo 11.
Create a purchase order to the supplier, add the product and add the discount. Confirm it and receive it.
· Current behavior
On purchase confirmation the price and discount are correct.
For example price unit is 100 €, discount 10%, price subtotal 90 €
Now, receive the goods, return to the purchase order,
The price unit is 90 €, discount 10% price subtotal 81 €
Expected behavior
Don't reapply the discount on the the price unit on product receive.

https://youtu.be/LfQ10AbsIU4

**Comment by pedrobaeza** [comment]
This is not happening in my tests. You should have something that is perverting the behavior. Please try in and record a video if reproducible:

https://runbot.odoo-community.org/runbot/142/11.0

**Comment by altoch** [comment]
> This is not happening in my tests. You should have something that is perverting the behavior. Please try in and record a video if reproducible:
> 
> https://runbot.odoo-community.org/runbot/142/11.0

I'm trying to validate a reception, it's giving me an error:
![image](https://user-images.githubusercontent.com/6033322/51173219-43f83d00-18b5-11e9-9263-329a3310a4b1.png)

**Comment by pedrobaeza** [comment]
This repository has landed cost activated. Just remove that part.

**Comment by altoch** [comment]
Ok, it's happening on your instance

**Comment by altoch** [comment]
Check Purchase Order
PO00011 and Purchase Order
PO00012

**Comment by altoch** [comment]
Sorry, I'm gonna record it.

**Comment by altoch** [comment]
https://www.youtube.com/watch?v=LfQ10AbsIU4&feature=youtu.be

**Comment by altoch** [comment]
> This is not happening in my tests. You should have something that is perverting the behavior. Please try in and record a video if reproducible:
> 
> https://runbot.odoo-community.org/runbot/142/11.0
Ok, it's happening on the runbot instance too, so it is not me
Check Purchase Order
PO00011,PO00012 and PO00013
The record:  https://youtu.be/LfQ10AbsIU4

**Comment by altoch** [comment]
If I remove from the models stock_move.py file and reinstall the module it works again like on 10.0

**Comment by altoch** [comment]
@pedrobaeza 
Buenos días Pedro, no se si lo viste pero deje el enlace al video, se reproduce el mismo problema en la instancia que montaste en runbot.
No quiero ser pesado, solo cerciorarme que tal y como me pediste puedas ver el video de 30 segundos,  supongo que tendrás cosas mucho más importantes.

**Comment by pedrobaeza** [comment]
I have seen it, but not being able to analyze.

**Comment by pedrobaeza** [comment]
This is fixed in 2ba8c549442e17b935a638ee74e6c638e9433c99
