### ISSUE TITLE
[11.0] Generated purchase request always gets requested by Administrator

### ISSUE THREAD

**Issue by altoch** [OCA/purchase-workflow#633]
module: purchase_request
version: 11.0

**Steps to reproduce**
Confirm a sales order that triggers a purchase request from any user different than default admin user
- ...

**Current behavior**
Requested user is always the default admin, not the one that confirmed the sales order or the assigned comercial.

**Expected behavior**
Set the request user to the sales order comercial or user that confirmed the sales order.

**Comment by altoch** [comment]
I did open a PR https://github.com/OCA/purchase-workflow/pull/640 but I'm not able to pass the tests

**Comment by HviorForgeFlow** [comment]
@altoch please confirm problem are properly solved in PR you proposed
