### ISSUE TITLE
[11.0][purchase_landed_cost] error when trying to add an item on "Import landed cost from pickings"

### ISSUE THREAD

**Issue by kurogeek** [OCA/purchase-workflow#670]
Hi,
I have tested the module purchase_landed_cost on Odoo 11. I got an error when I was trying to "Import landed cost from pickings" from vendor bills. 

Step to reproduce the error. Go to Purchases -> vendor bills -> select any vendor bill -> click on Landed costs tab -> click on "IMPORT FROM PICKINGS" -> then try to add an item.

And we will have this error.

Error:
Error: TypeError: 'float' object is unsubscriptable

http://127.18.10.7:8069/web/content/384-6d50330/web.assets_backend.js:181
Traceback:
py.PY_getItem@http://127.18.10.7:8069/web/content/384-6d50330/web.assets_backend.js:181:73
py.evaluate@http://127.18.10.7:8069/web/content/384-6d50330/web.assets_backend.js:266:71
py.evaluate@http://127.18.10.7:8069/web/content/384-6d50330/web.assets_backend.js:265:108
py.evaluate@http://127.18.10.7:8069/web/content/384-6d50330/web.assets_backend.js:267:96
py.eval@http://127.18.10.7:8069/web/content/384-6d50330/web.assets_backend.js:272:281
eval_domains/<@http://127.18.10.7:8069/web/content/384-6d50330/web.assets_backend.js:380:133
_.forEach@http://127.18.10.7:8069/web/content/371-de33e53/web.assets_common.js:12:558
_.mixin/</_.prototype[name]@http://127.18.10.7:8069/web/content/371-de33e53/web.assets_common.js:69:521
eval_domains@http://127.18.10.7:8069/web/content/384-6d50330/web.assets_backend.js:379:265
pyeval@http://127.18.10.7:8069/web/content/384-6d50330/web.assets_backend.js:393:24
stringToArray@http://127.18.10.7:8069/web/content/384-6d50330/web.assets_backend.js:296:666
_getDomain@http://127.18.10.7:8069/web/content/384-6d50330/web.assets_backend.js:1236:81
_onAddRecord@http://127.18.10.7:8069/web/content/384-6d50330/web.assets_backend.js:1058:1585
proxy/<@http://127.18.10.7:8069/web/content/371-de33e53/web.assets_common.js:3923:8
trigger@http://127.18.10.7:8069/web/content/371-de33e53/web.assets_common.js:3921:166
_trigger_up@http://127.18.10.7:8069/web/content/371-de33e53/web.assets_common.js:3927:340
_trigger_up@http://127.18.10.7:8069/web/content/371-de33e53/web.assets_common.js:3927:442
trigger_up@http://127.18.10.7:8069/web/content/371-de33e53/web.assets_common.js:3927:275
_onAddRecord/<@http://127.18.10.7:8069/web/content/384-6d50330/web.assets_backend.js:1615:242
then/</</<@http://127.18.10.7:8069/web/content/371-de33e53/web.assets_common.js:802:678
fire@http://127.18.10.7:8069/web/content/371-de33e53/web.assets_common.js:796:281
add@http://127.18.10.7:8069/web/content/371-de33e53/web.assets_common.js:797:467
then/</<@http://127.18.10.7:8069/web/content/371-de33e53/web.assets_common.js:802:649
each@http://127.18.10.7:8069/web/content/371-de33e53/web.assets_common.js:625:758
then/<@http://127.18.10.7:8069/web/content/371-de33e53/web.assets_common.js:802:553
Deferred@http://127.18.10.7:8069/web/content/371-de33e53/web.assets_common.js:803:189
then@http://127.18.10.7:8069/web/content/371-de33e53/web.assets_common.js:802:518
_onAddRecord@http://127.18.10.7:8069/web/content/384-6d50330/web.assets_backend.js:1615:226
proxy/<@http://127.18.10.7:8069/web/content/371-de33e53/web.assets_common.js:3923:8
dispatch@http://127.18.10.7:8069/web/content/371-de33e53/web.assets_common.js:892:378
add/elemData.handle@http://127.18.10.7:8069/web/content/371-de33e53/web.assets_common.js:865:151

Ps. On the server logs there is no sign of error on the server side when this happened.

**Comment by pedrobaeza** [comment]
Should be fixed in 59a54948189f3da66f15de20e6edc55e5d0ffef1
