### ISSUE TITLE
[11.0][purchase_request] Expected singleton in _compute_line_count

### ISSUE THREAD

**Issue by livingmine** [OCA/purchase-workflow#683]
**Steps to reproduce**
Browse the ```line_count``` field from purchase request records so that ```_compute_line_count``` is triggered.

**Current behavior**
Error expected singleton is thrown. Simply because the method is not using ```for rec in self``` in the beginning of the code.

**Expected behavior**
No error is thrown.

Is there any reason why there is no ```for rec in self``` in the beginning of this method?

**Comment by LoisRForgeFlow** [comment]
You are correct, please could you open a PR to fix it?
