### ISSUE TITLE
Wrong Discount Total on Purchase Analysis Report

### ISSUE THREAD

**Issue by usmanfarzandali** [OCA/purchase-workflow#714]
module: purchase_discount
version: 12.0

![imageedit_128_5073994774](https://user-images.githubusercontent.com/22232100/60895310-d7676500-a27d-11e9-8689-c86179220149.gif)

**Comment by pedrobaeza** [comment]
The value put there is never going to be correct, as there's no formula for properly aggregate this value. Sum is not correct, but neither the average, and you can't totalize by any other way there.

If you want to add a comment in the README about this, a PR is welcome, but as said, this can't be fixed.

**Comment by usmanfarzandali** [comment]
![imageedit_134_9758599113](https://user-images.githubusercontent.com/22232100/60900701-0e417900-a286-11e9-89c2-93247df98069.gif)

i don't know my code meet OCA Code Standard 
but after minor modification my code working well .....
and also added one more field name Discount Amt

**Comment by pedrobaeza** [comment]
But what happen when you have several purchases for the same product?

**Comment by usmanfarzandali** [comment]
let me more testing ....
