### ISSUE TITLE
purchase_landed_cost: no stock revaluation stock account posting

### ISSUE THREAD

**Issue by ccandito** [OCA/purchase-workflow#758]
Dear All,
when changing the product unit price, a revaluation stock account posting is necessary as Odoo standard does in "update cost" in product cost.
Regards
claudio

**Comment by pedrobaeza** [comment]
Module still doesn't covered this use case.

**Comment by ccandito** [comment]
Thanks for your replay.
Yes, i know.
Without this feature the stock accounting is not aligned with logistica.
Regards
Claudio candito

Il giorno dom 6 ott 2019 alle 13:42 Pedro M. Baeza <notifications@github.com>
ha scritto:
