### ISSUE TITLE
[IMP] purchase_request, lack of field analytic_tag_ids on line.

### ISSUE THREAD

**Issue by kittiu** [OCA/purchase-workflow#766]
@hveficent @aheficent 
Hello, I noticed that purchase.request.line do not have field analytic_tag_ids, while all other standard document, from expense, sale, purchase, invoice do have it.
Can we have it? (I can help doing it).
Note: we also need it to be used on what we developing on budget commitment on PR.
cc @ps-tubtim

**Comment by AaronHForgeFlow** [comment]
Hi @kittiu, I think this would be a nice feature and it integrates well in Odoo as we have analytic tags in many documents. Just one thing, some companies does not use analytic tags. Thus, it would be nice if we can include an option to activate analytic tags or not depending on the use case.

**Comment by kittiu** [comment]
@aheficent we will make the PR, following the same way as other document.
Thanks!

**Comment by AaronHForgeFlow** [comment]
That is great. Thank you.

**Comment by kittiu** [comment]
@Saran440 can you help?
