### ISSUE TITLE
[12.0][MIG] procurement_purchase_no_grouping: it doesnt't work properly

### ISSUE THREAD

**Issue by ghost** [OCA/purchase-workflow#776]
I have created a new product "Service"  Type and I have configurated to buy automatically when the product is added to a sale order. 
![04](https://user-images.githubusercontent.com/25029267/67584889-de43b600-f74e-11e9-94e9-6e561621bd26.png)

 I have added it to a new category with the value "No order grouping"
![02](https://user-images.githubusercontent.com/25029267/67584953-f61b3a00-f74e-11e9-994c-fb0df9c0a3ec.png)

I have created 2 sale orders and they have been groupped.
![03](https://user-images.githubusercontent.com/25029267/67585016-0cc19100-f74f-11e9-909d-6029795a1eac.png)
![05](https://user-images.githubusercontent.com/25029267/67585059-2236bb00-f74f-11e9-8069-fad34095e37a.png)

I have tried to test it on runbot but I haven't can be able to rebuild the data base of the issue #702

Is it a bug?

**Comment by pedrobaeza** [comment]
Services don't follow the same flow than goods one. An special bridge must be developed for that. Feel free to add that to the ROADMAP of the module.
