### ISSUE TITLE
purchase_requisition_multicurrency & purchase_requisition_bid_selecton: Both modules declare "price list" and add it to the view of purchase.requisition

### ISSUE THREAD

**Issue by ybofr** [OCA/purchase-workflow#79]
Hi,

I'm new to the module. So there are two fields with the same description and no field help to explain what is the difference between the two fields.

**Comment by pedrobaeza** [comment]
Where? Which module?

**Comment by yvaucher** [comment]
@ybofr The module purchase_requisition_multicurrency adds a field pricelist_id on purchase_requisition but I'm not aware of a second field with same name. Can you provide a print screen and tell if you have installed any other module that could also add this field?

**Comment by ybofr** [comment]
We have installed the following modules:
1. purchase_requisition_bid_selection
2. /purchase_requisition_multicurrency
3. /purchase_partner_invoice_method
4./purchase_rfq_bid_workflow

Screenshot attached
![calls_for_bids_-_odoo](https://cloud.githubusercontent.com/assets/7601880/5665123/15d68b62-974e-11e4-998c-7f5af417acae.png)

**Comment by yvaucher** [comment]
Ok got it.

https://github.com/OCA/purchase-workflow/blob/8.0/purchase_requisition_multicurrency/view/purchase_requisition.xml#L12
https://github.com/OCA/purchase-workflow/blob/8.0/purchase_requisition_bid_selection/view/purchase_requisition.xml#L35

purchase_requisition_bid_selection also adds pricelist_id on purchase.requisition.

This is an uncompatibility between the two modules.
