### ISSUE TITLE
purchase_requisition_multicurrency: Cannot enter a bid in foreign currency

### ISSUE THREAD

**Issue by ybofr** [OCA/purchase-workflow#80]
The system does not allow me to enter a bid in a foreign currency.

I have 2 purchase price lists. one in use and one in euro. When I choose my usd price list in my bid (created via a call for bid), the system automatically changes it in EUR, not letting me enter the price in USD.

Thanks for help

**Comment by pedrobaeza** [comment]
You have to indicate the module in the title, because each repo can contain more than one module.

**Comment by ybofr** [comment]
Done. Sorry, I thought it was under the module name.

Thanks for the advice

**Comment by yvaucher** [comment]
@ybofr Are you trying to change currency field ? This is a uneditable field as it is related to pricelist.

I guess you do not see the field pricelist on bid because you need to enable
`Settings/Configuration/Purchases -> Manage pricelist per supplier`

**Comment by ybofr** [comment]
No, I see the field pricelist. The problem is, I have a pricelist in ANG and the system forces the bid currency USD, thus preventing me to use any other currency.
Sceenshot attached
![1 requests_for_quotation_-_odoo](https://cloud.githubusercontent.com/assets/7601880/5665279/3a3cb46c-974f-11e4-96a7-605b5312cbb2.png)

**Comment by yvaucher** [comment]
I see it might be an issue with pricelist onchange changing value of a readonly field.

Is you field currency_id editable?

After having tried `purchase_requisition_multicurrency` on last OCA/OCB I can tell onchange is working fine.
I think this issue comes from another module setting currency_id readonly.

What is the list of addons you use to extend purchase order?

**Comment by ybofr** [comment]
We have installed the following modules:
1. purchase_requisition_bid_selection
2. /purchase_requisition_multicurrency
3. /purchase_partner_invoice_method
4./purchase_rfq_bid_workflow

**Comment by yvaucher** [comment]
I just tried it on runbot and this bug seems present on official modules

I created the following issue:
https://github.com/odoo/odoo/issues/4598

You might want to complete it.

Thus I close this bug report.

**Comment by lepistone** [comment]
@ybofr I think #88 addresses the problem. I think a similar fix can be done for the core purchase module.
