### ISSUE TITLE
purchase_requisition_bid_selection: Confusion in the naming of the button

### ISSUE THREAD

**Issue by ybofr** [OCA/purchase-workflow#81]
This is the description of the functionality: "First, a list of products is established. The call for bid is then confirmed and RFQs can be generated. They are in the state 'Draft RFQ' until sent to the supplier and then marked as 'RFQ Sent'. The bids have to be encoded and moved to state 'Bid Encoded'. When closing the call for bids, in order to start the bids selection, all RFQ that have not been sent will be canceled. However, sent RFQs can still be encoded. Bids that are not received will remain in state 'RFQ Sent' and can be manually canceled."

The problem is that there is no field called "generate bid". The only field is called "encode bid". This creates a confusion by the user as it implies that the bid must be encoded immediately, without doing anything else.

**Comment by pedrobaeza** [comment]
I don't see any problem. The description says: _The bids have to be encoded and moved to state 'Bid Encoded'_ and thus, the button is _Encode bid_. Anyways, this is standard Odoo, so if you find any other problem related, you have to publish the issue on Odoo itself.

**Comment by ybofr** [comment]
No, the problem is that in the standard Odoo, there is a button called "request a quotation". This button kind of disappear when this module is installed, leaving only "encode bid" button there. There is a difference between standard Odoo and this module.
So the term "encode bid" is not found in Odoo V8, only in this OCA module.
But, at the start of the process, you want first to request a quotation, then encode the bid when you receive it. So, this is why I find it confusing.

**Comment by pedrobaeza** [comment]
OK, I see, can you please edit the title to indicate in which module is happening the issue?

**Comment by ybofr** [comment]
Done

**Comment by gurneyalex** [comment]
@ybofr this is by design of this addon. You have a button to generate a bid when your purchase requisition is in call for bid mode "Closed", in which case you can select the suppliers you want to ask a bid from and generate a call for bid. In "Open" mode, it is assumed that you are publishing your tender on a public platform and you will receive bids from suppliers that you will indeed encode.
