### ISSUE TITLE
 [12.0][Subcontracting Service] 

### ISSUE THREAD

**Issue by morekvn** [OCA/purchase-workflow#818]
I can't operate the "Subcontracting Service" module once installed, I modified a "Product" and duplicated a "SalesOrder" 
( "storable" products and sales order that works before, they do create a "request for quotation" ):

Change the Product Type to "Service".
Tick the "Subcontracted Service" box
Add a "Vendors"

I create a Sales Order but no Request for Quotation is created.
I have looked in my warehouses, the rule "Subcontracting service rule" is well present in "Buy"

Do you have any idea how to make this work?

Thank you

**Comment by hitrosol** [comment]
I have the same question, but related to the subcontracting in manufacturing.  We need more detail about how use it in the in Readme file.
