### ISSUE TITLE
[12.0] Purchase triple discount error in runbot

### ISSUE THREAD

**Issue by manuelcalerosolis** [OCA/purchase-workflow#834]
Working with this module we have discovered an error that also occurs in the runbot.

We create a new purchase with the following data.

units: 48
Price: 0.33
discount: 5%
total order: 15,05

![image](https://user-images.githubusercontent.com/3088246/71409638-a4a20500-2642-11ea-932e-53fe3abe820d.png)

These calculations are correct.

We confirm the budget, and receive the products.

![image](https://user-images.githubusercontent.com/3088246/71409795-167a4e80-2643-11ea-9134-126088ad112d.png)

The price of the order is still good.

If we make the invoice, we see that the amount has changed.

![image](https://user-images.githubusercontent.com/3088246/71409925-8a1c5b80-2643-11ea-8d5a-26d045e85b7c.png)

We are trying to check the calculations to see where the error occurs.

Regards.

**Comment by legalsylvain** [comment]
Check rounding errors. 
See : 
48 * .33 * .95  = 15.05....
48 * round(.33 * .95, 2)  = 14.88...

**Comment by manuelcalerosolis** [comment]
If I uninstall the modules "tripe_discount" the calculations are correct.

![image](https://user-images.githubusercontent.com/3088246/71411999-e5524c00-264b-11ea-902d-050b4dd2de3f.png)

Something is wrong with these modules.

**Comment by manuelcalerosolis** [comment]
The only solution is to completely rewrite the method "_compute_price".

I know it is not a good idea, possible changes in this method will not be contemplated, and this is dangerous.

The ideal would be to propose a change so that the price of the product already with discounts is in a single method, and the code is not so coupled.

Do you think anyone would listen to this proposal? 

class AccountInvoiceLine(models.Model):
    _inherit = "account.invoice.line"

    discount2 = fields.Float(
        'Discount 2 (%)',
        digits=dp.get_precision('Discount'),
    )
    discount3 = fields.Float(
        'Discount 3 (%)',
        digits=dp.get_precision('Discount'),
    )

    @api.multi
    @api.depends('discount2', 'discount3')
    def _compute_price(self):
        currency = self.invoice_id and self.invoice_id.currency_id or None
        
        # to avoid coupling these calculations must be passed to a method 
        price = self.price_unit * (1 - (self.discount or 0.0) / 100.0)
        price *= (1 - (self.discount2 or 0.0) / 100.0)
        price *= (1 - (self.discount3 or 0.0) / 100.0)

        taxes = False
        if self.invoice_line_tax_ids:
            taxes = self.invoice_line_tax_ids.compute_all(price, currency, self.quantity, product=self.product_id,
                                                          partner=self.invoice_id.partner_id)
        self.price_subtotal = price_subtotal_signed = taxes['total_excluded'] if taxes else self.quantity * price
        self.price_total = taxes['total_included'] if taxes else self.price_subtotal
        if self.invoice_id.currency_id and self.invoice_id.currency_id != self.invoice_id.company_id.currency_id:
            currency = self.invoice_id.currency_id
            date = self.invoice_id._get_currency_rate_date()
            price_subtotal_signed = currency._convert(price_subtotal_signed, self.invoice_id.company_id.currency_id,
                                                      self.company_id or self.env.user.company_id,
                                                      date or fields.Date.today())
        sign = self.invoice_id.type in ['in_refund', 'out_refund'] and -1 or 1
        self.price_subtotal_signed = price_subtotal_signed * sign`
