### ISSUE TITLE
Question on purchase_triple_discount

### ISSUE THREAD

**Issue by Cedric-Pigeon** [OCA/purchase-workflow#848]
Hi Community,

I have currently a need for one of my customers to manage triple discounts on purchase order.
I had a look at purchase_triple_discount and it seems to be a good clue.
The only difference is that my customer manages its discounts depending on qty levels.
Example:
Purchase price : 50 €/Pc
Discount 1: 10 PC -> 20%
Discount 2: 20 Pc -> 10 %
....
Order for 8 PC: 8 x 50 = 400
Order for 11 PC: 11 x 50 = 550 - 20% = 440
Order for 25 PC:  25 x 50 = 1250 - 20 % = 1000 - 10 % = 900

Am I wrong or the addon does not exactly work like that?

**Comment by Cedric-Pigeon** [comment]
@pedrobaeza Any opinion on that?

**Comment by pedrobaeza** [comment]
It should work thanks to this code:

https://github.com/OCA/purchase-workflow/blob/c237c9a6aca03dfa17cdcd45ebb49776892ff43c/purchase_triple_discount/models/purchase_order.py#L41-L46

**Comment by legalsylvain** [comment]
It should perfectly work.

**Comment by Cedric-Pigeon** [comment]
Yes now I got it.

Thanks a lot for your clue.
