### ISSUE TITLE
[11.0] purchase_discount rounding error

### ISSUE THREAD

**Issue by firmanazis** [OCA/purchase-workflow#850]
The way purchase_discount module compute discount has bug that may cause inaccurate rounding, due to rounding when assign discounted price to line.price_unit. Especially if the price_unit * discount results a float number with decimal digits more than what defined on 'Product Price' of Decimal Accuracy (decimal.precision model). For example 30% * 50.26 = 35.18**2**.

```
    def _compute_amount(self):
        for line in self:
            price_unit = False
            # This is always executed for allowing other modules to use this
            # with different conditions than discount != 0
            price = line._get_discounted_price_unit()
            if price != line.price_unit:
                # Only change value if it's different
                price_unit = line.price_unit
                line.price_unit = price  # this may cause inaccurate rounding
            super(PurchaseOrderLine, line)._compute_amount()
            if price_unit:
                line.price_unit = price_unit
```

One workaround is obviously to increase digits defined in Settings/Technical/Decimal Accuracy/Product Price, but this results ugly Purchase Order pdf when printed, because the price_unit decimal digits increase.

I suggest to change the price_unit digits before looping line records. Here is my fix, I wrote a 'purchase_discount_fix' that temporarily increase decimal digits, and then restore it after _compute_amount finished.

```
class PurchaseOrderLine(models.Model):
    _inherit = "purchase.order.line"

    @api.depends('discount')
    def _compute_amount(self):
        field_price_unit = self._fields['price_unit']
        temp_price_unit_digits = field_price_unit._digits
        field_price_unit._digits = (20,6)

        super(PurchaseOrderLine, self)._compute_amount() # invoke purchase_discount _compute_amount

        field_price_unit._digits = temp_price_unit_digits
```

**Comment by vincent-hatakeyama** [comment]
I think #686 solves that issue.
