### ISSUE TITLE
[12.0]purchase_order_line_deep_sort  Add a module for sales order?

### ISSUE THREAD

**Issue by zlobb** [OCA/purchase-workflow#858]
https://github.com/OCA/purchase-workflow/tree/12.0/purchase_order_line_deep_sort
Hi,
Add a module for sales order?

**Comment by pedrobaeza** [comment]
There isn't such module for now.

**Comment by zlobb** [comment]
How can such modules be developed, or paid for?

**Comment by pedrobaeza** [comment]
You can ask on contributors list if someone wants to develop it.

**Comment by zlobb** [comment]
ok,
thank you.
