### ISSUE TITLE
Cannot view the completed order, and there is no order type

### ISSUE THREAD

**Issue by HAISON2019** [OCA/purchase-workflow#869]
module: purchase_order_type
version: 12.0

**Steps to reproduce**
After the "purchase_order_type" module is installed, the previously completed order cannot be edited. It is prompted to fill in the order type, but it cannot be selected after re-editing.
- ...

**Current behavior**

**Expected behavior**

**Comment by HviorForgeFlow** [comment]
As there is no way to know which order_type is going on each purchase that is already completed, it can't be performed as a migration script.

You cannot perform the action as completed purchases are in state done. You could try defining a server action that writes that field. It may do the trick.

@nicomacr Why default is defined this way? https://github.com/OCA/purchase-workflow/blob/4bdc05e655cda491ff763843979395b7d88010c8/purchase_order_type/models/purchase_order.py#L11-L12 it seems doing a search without filters and limit 1 is not so accurate.
