### ISSUE TITLE
[12.0]purchase_deposit，Conflict with other modules

### ISSUE THREAD

**Issue by qzmxs** [OCA/purchase-workflow#879]
module: purchase_deposit
version: 12.0

**Steps to reproduce**
- ...
purchase_deposit with [purchase_stock_picking_return_invoicing] Conflict modules
**Current behavior**
There is no problem installing these two modules separately. If the combined installation prevents the (product) bill from being created, you can only create (prepay) the product.
**Expected behavior**

**Comment by pedrobaeza** [comment]
Please don't duplicate the same issue in both repos, and more without enough information. Closing this one for continuing in the other.
