### ISSUE TITLE
Purchase Open Qty doesn't correctly deal with units

### ISSUE THREAD

**Issue by uncle-buzz** [OCA/purchase-workflow#918]
Odoo 12.0, with module Purchase Open Qty, On a purchase order, product_qty qty_received qty_to_invoice and qty_invoiced fields depend on product_uom field (dozen by example) on the line, but qty_to_received depends of units in product configuration (unit by example) (I presume, I did'nt check where .

So if I purchase 1 hundred of products and receive 100 units, all fields are correct (1 (hundred) or 0)apart from qty_to_received who say 99 = 100 (units) - 1 (hundred).

If I purchase 1 dozen and receive 6 units, all fields are correct (0.5 (dozen) or 0) apart from qty_to_received who say 11.5 = 12 (units) - 0.5 (dozen)

**Comment by uncle-buzz** [comment]
```python
    def _compute_qty_to_receive(self):
        for line in self:
            total = line.product_uom_qty
            for move in line.move_ids.filtered(
                    lambda m: m.state == 'done'):
                if move.product_uom != line.product_uom:
                    total -= move.product_uom._compute_quantity(
                        move.product_uom_qty, line.product_uom)
                else:
                    total -= move.product_uom_qty
            line.qty_to_receive = total
```

**line.product_uom_qty** stores the quantity of product depending on the unit set in product_template, **line.product_qty** is the quantity of product depending on the unit set in the purchase order line in **line.product_uom**.
We shouldn't use **line.product_uom_qty** as total and removing move values converted to **line.product_uom** since they don't have the same unit.
Replacing **line.product_uom_qty** by **line.product_qty** gives correct result, **qty_to_receive** will be convert to **line.product_uom** like other values.

**Comment by HviorForgeFlow** [comment]
Hello @uncle-buzz, it would be great if you could propose this fix as a PR. Thanks!

**Comment by uncle-buzz** [comment]
I'm new to GitHub and I don't know how doing this... And I'm new to odoo also, I'm not sure the correction I tried is the correct one, if it's conform to the meaning of these fields and if there is no side effect...
It would be probably a better thing to let some experts about this module to valid or find another way to deal with this issue...

**Comment by luisbernalgms** [comment]
Hello @uncle-buzz 

I have a similiar problem. Did you solve it?

**Comment by yrismawan** [comment]
I think it's already fixed on V.13
