### ISSUE TITLE
purchase_requisition_bid_selection: Bids selection I guess `.name` missing somewhere!

### ISSUE THREAD

**Issue by petrus-v** [OCA/purchase-workflow#95]
Test on v8 only

Using the module purchase_requisition_bid_selection, when selecting products line (click on "Choose product line" in call for bids form). On the grouped line it's display "product.product(4,)" instead the name_get() result.

**Comment by yvaucher** [comment]
I confirm this issue. Thanks for reporting it

**Comment by petrus-v** [comment]
With pleasure, as you van see I made PR#98 to fix it.

Regards,

**Comment by yvaucher** [comment]
(@petrus-v a github tip just write #98 to make a link to your pr)

**Comment by petrus-v** [comment]
@yvaucher thanks for the tip!
