### ISSUE TITLE
[11.0, 12.0] purchase_landed_cost only working for cost type average

### ISSUE THREAD

**Issue by jjscarafia** [OCA/purchase-workflow#964]
Is there any reason why this module is only working for cost_method = average?
Check [this line](https://github.com/OCA/purchase-workflow/blob/11.0/purchase_landed_cost/models/purchase_cost_distribution.py#L271)

@pedrobaeza any idea about this?
Thanks!

**Comment by pedrobaeza** [comment]
The module is simply not prepared for other costing methods. For the others, you have stock_landed_cost

**Comment by jjscarafia** [comment]
Thanks
