### ISSUE TITLE
[13.0]purchase_blanket_order Add product in editing state, report error

### ISSUE THREAD

**Issue by qzmxs** [OCA/purchase-workflow#990]
After confirmation->Cancel->Draft->Add product in editing state, report error

**Comment by qzmxs** [comment]
![image](https://user-images.githubusercontent.com/55458897/95241860-f964e400-0840-11eb-8ae0-11954cdc8539.png)
![image](https://user-images.githubusercontent.com/55458897/95241965-23b6a180-0841-11eb-9acf-4de03b8f80fc.png)
![image](https://user-images.githubusercontent.com/55458897/95242071-43e66080-0841-11eb-8e2c-a58b4f4843bf.png)
![image](https://user-images.githubusercontent.com/55458897/95242170-64161f80-0841-11eb-8625-fa5c1b419d48.png)
![image](https://user-images.githubusercontent.com/55458897/95242295-9031a080-0841-11eb-9959-15074090c12b.png)
![image](https://user-images.githubusercontent.com/55458897/95242405-b35c5000-0841-11eb-84af-b9b2f93d31e3.png)
![image](https://user-images.githubusercontent.com/55458897/95242515-dedf3a80-0841-11eb-9c48-7fa883b6356f.png)
![image](https://user-images.githubusercontent.com/55458897/95242605-f9b1af00-0841-11eb-85a6-ffd1aae32f31.png)

**Comment by qzmxs** [comment]
This problem has been verified repeatedly and the fault remains

**Comment by HviorForgeFlow** [comment]
Hello @qzmxs ,
I tried to fix it with no success. 

I think it is something related with the Add Item button that should be created in the line below the one you recently edit, but just guessing.

Let's see if someone can find a way to fix it
